-- Phase 39b Wave 0 — catalog bootstrap (one-shot data seed).
-- Generated by scripts/build-seed-sql.mjs from scripts/watch-seed-data.md
-- Idempotent: every INSERT uses ON CONFLICT DO NOTHING.
-- Counts: 11 brands, 32 families, 100 catalog rows, 52 lineage edges.

BEGIN;

-- ----- 1. brands (11) -----
INSERT INTO brands (name, slug, country_of_origin) VALUES
  ('Rolex', 'rolex', 'Switzerland'),
  ('Omega', 'omega', 'Switzerland'),
  ('Audemars Piguet', 'audemars-piguet', 'Switzerland'),
  ('Tudor', 'tudor', 'Switzerland'),
  ('Squale', 'squale', 'Switzerland'),
  ('Christopher Ward', 'christopher-ward', 'United Kingdom'),
  ('Steinhart', 'steinhart', 'Germany'),
  ('Swatch', 'swatch', 'Switzerland'),
  ('Longines', 'longines', 'Switzerland'),
  ('Seiko', 'seiko', 'Japan'),
  ('Grand Seiko', 'grand-seiko', 'Japan')
ON CONFLICT (name_normalized) DO NOTHING;

-- ----- 2. watch_families (32) -----
INSERT INTO watch_families (brand_id, name)
SELECT b.id, v.family_name
FROM (VALUES
  ('Rolex', 'Submariner'),
  ('Rolex', 'Sea-Dweller'),
  ('Rolex', 'GMT-Master II'),
  ('Rolex', 'Daytona'),
  ('Rolex', 'Explorer'),
  ('Rolex', 'Datejust'),
  ('Omega', 'Speedmaster Moonwatch'),
  ('Omega', 'Seamaster Diver 300M'),
  ('Omega', 'Seamaster Planet Ocean'),
  ('Omega', 'Constellation'),
  ('Audemars Piguet', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak Offshore'),
  ('Tudor', 'Black Bay'),
  ('Tudor', 'Pelagos'),
  ('Squale', '1521'),
  ('Christopher Ward', 'C60 Trident'),
  ('Steinhart', 'Ocean'),
  ('Swatch', 'MoonSwatch'),
  ('Longines', 'Legend Diver'),
  ('Longines', 'Heritage Military'),
  ('Longines', 'Spirit'),
  ('Longines', 'HydroConquest'),
  ('Seiko', 'Prospex Marinemaster'),
  ('Seiko', 'Prospex Turtle'),
  ('Seiko', 'Prospex Sumo'),
  ('Seiko', '5 Sports'),
  ('Seiko', 'SKX'),
  ('Seiko', 'Alpinist'),
  ('Grand Seiko', 'Heritage'),
  ('Grand Seiko', 'Evolution 9'),
  ('Grand Seiko', 'Sport'),
  ('Grand Seiko', 'Elegance')
) AS v(brand_name, family_name)
JOIN brands b ON b.name_normalized = lower(trim(v.brand_name))
ON CONFLICT (brand_id, name_normalized) DO NOTHING;

-- ----- 3. watches_catalog (100) -----
INSERT INTO watches_catalog (brand, model, reference, family_id, brand_id, source)
SELECT v.brand, v.model, v.reference, wf.id, b.id, 'admin_curated'
FROM (VALUES
  ('Rolex', 'Submariner Date', '126610LN', 'Submariner'),
  ('Rolex', 'Submariner Date', '116610LN', 'Submariner'),
  ('Rolex', 'Submariner Date', '16610', 'Submariner'),
  ('Rolex', 'Submariner Date', '16800', 'Submariner'),
  ('Rolex', 'Submariner No-Date', '124060', 'Submariner'),
  ('Rolex', 'Submariner No-Date', '114060', 'Submariner'),
  ('Rolex', 'Submariner No-Date', '14060M', 'Submariner'),
  ('Rolex', 'Submariner', '5513', 'Submariner'),
  ('Rolex', 'Sea-Dweller', '126600', 'Sea-Dweller'),
  ('Rolex', 'Sea-Dweller', '116600', 'Sea-Dweller'),
  ('Rolex', 'Sea-Dweller', '16600', 'Sea-Dweller'),
  ('Rolex', 'Sea-Dweller', '1665', 'Sea-Dweller'),
  ('Rolex', 'GMT-Master II', '126710BLRO', 'GMT-Master II'),
  ('Rolex', 'GMT-Master II', '126710BLNR', 'GMT-Master II'),
  ('Rolex', 'GMT-Master II', '116710LN', 'GMT-Master II'),
  ('Rolex', 'GMT-Master II', '16710', 'GMT-Master II'),
  ('Rolex', 'GMT-Master', '1675', 'GMT-Master II'),
  ('Rolex', 'Cosmograph Daytona', '126500LN', 'Daytona'),
  ('Rolex', 'Cosmograph Daytona', '116500LN', 'Daytona'),
  ('Rolex', 'Cosmograph Daytona', '116520', 'Daytona'),
  ('Rolex', 'Cosmograph Daytona', '16520', 'Daytona'),
  ('Rolex', 'Cosmograph Daytona', '6263', 'Daytona'),
  ('Rolex', 'Explorer', '124270', 'Explorer'),
  ('Rolex', 'Explorer', '214270', 'Explorer'),
  ('Rolex', 'Explorer', '1016', 'Explorer'),
  ('Rolex', 'Datejust 36', '126234', 'Datejust'),
  ('Rolex', 'Datejust 36', '116234', 'Datejust'),
  ('Omega', 'Speedmaster Moonwatch', '310.30.42.50.01.001', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Moonwatch', '311.30.42.30.01.005', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Professional', '3570.50', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Professional', '3590.50', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Professional', '145.022', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Professional', '145.012', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster Professional', '105.012', 'Speedmaster Moonwatch'),
  ('Omega', 'Speedmaster', 'CK2998', 'Speedmaster Moonwatch'),
  ('Omega', 'Seamaster Diver 300M', '210.30.42.20.01.001', 'Seamaster Diver 300M'),
  ('Omega', 'Seamaster Diver 300M', '212.30.41.20.01.003', 'Seamaster Diver 300M'),
  ('Omega', 'Seamaster Diver 300M', '2531.80', 'Seamaster Diver 300M'),
  ('Omega', 'Seamaster Planet Ocean', '215.30.44.21.01.001', 'Seamaster Planet Ocean'),
  ('Omega', 'Seamaster Planet Ocean', '2200.50', 'Seamaster Planet Ocean'),
  ('Omega', 'Constellation', '168.005', 'Constellation'),
  ('Omega', 'Constellation Globemaster', '130.33.39.21.02.001', 'Constellation'),
  ('Audemars Piguet', 'Royal Oak Jumbo Extra-Thin', '15202ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak Jumbo Extra-Thin', '16202ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak', '15500ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak', '15400ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak', '15300ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak', '14790ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak', '5402ST', 'Royal Oak'),
  ('Audemars Piguet', 'Royal Oak Offshore', '25721ST', 'Royal Oak Offshore'),
  ('Audemars Piguet', 'Royal Oak Offshore', '26470ST', 'Royal Oak Offshore'),
  ('Audemars Piguet', 'Royal Oak Offshore', '26420SO', 'Royal Oak Offshore'),
  ('Tudor', 'Black Bay', '79230N', 'Black Bay'),
  ('Tudor', 'Black Bay 58', '79030N', 'Black Bay'),
  ('Tudor', 'Black Bay GMT', '79830RB', 'Black Bay'),
  ('Tudor', 'Black Bay Pro', '79470', 'Black Bay'),
  ('Tudor', 'Black Bay Chrono', '79360N', 'Black Bay'),
  ('Tudor', 'Pelagos', '25600TN', 'Pelagos'),
  ('Tudor', 'Pelagos 39', '25407N', 'Pelagos'),
  ('Squale', '1521 Classic', '1521-026', '1521'),
  ('Christopher Ward', 'C60 Trident Pro 600', 'C60-300', 'C60 Trident'),
  ('Christopher Ward', 'C60 Trident Pro 300', 'C60-LDP38', 'C60 Trident'),
  ('Steinhart', 'Ocean One 39', 'Ocean-One-39', 'Ocean'),
  ('Steinhart', 'Ocean Vintage Military', 'Ocean-OVM', 'Ocean'),
  ('Swatch', 'MoonSwatch Mission to the Moon', 'SO33M100', 'MoonSwatch'),
  ('Swatch', 'MoonSwatch Mission to Mars', 'SO33A100', 'MoonSwatch'),
  ('Swatch', 'MoonSwatch Mission to Earth', 'SO33G100', 'MoonSwatch'),
  ('Longines', 'Legend Diver', 'L3.674.4.50.0', 'Legend Diver'),
  ('Longines', 'Legend Diver', 'L3.774.4.50.9', 'Legend Diver'),
  ('Longines', 'Heritage Military COSD', 'L2.832.4.53.0', 'Heritage Military'),
  ('Longines', 'Heritage Military 1938', 'L2.788.1.53.0', 'Heritage Military'),
  ('Longines', 'Spirit 40mm', 'L3.810.4.53.0', 'Spirit'),
  ('Longines', 'Spirit Zulu Time', 'L3.812.4.63.6', 'Spirit'),
  ('Longines', 'HydroConquest 39mm', 'L3.781.4.06.6', 'HydroConquest'),
  ('Longines', 'HydroConquest 41mm', 'L3.880.4.16.2', 'HydroConquest'),
  ('Seiko', 'Prospex', 'SLA017', 'Prospex Marinemaster'),
  ('Seiko', 'Prospex', 'SLA033', 'Prospex Marinemaster'),
  ('Seiko', '62MAS', '6217-8001', 'Prospex Marinemaster'),
  ('Seiko', '6105-8110', '6105-8110', 'Prospex Marinemaster'),
  ('Seiko', 'Prospex Turtle', 'SRP777', 'Prospex Turtle'),
  ('Seiko', 'Prospex Turtle', 'SRPE93', 'Prospex Turtle'),
  ('Seiko', '6309-7040', '6309-7040', 'Prospex Turtle'),
  ('Seiko', 'Prospex Sumo', 'SPB101', 'Prospex Sumo'),
  ('Seiko', 'Prospex Sumo', 'SBDC001', 'Prospex Sumo'),
  ('Seiko', '5 Sports', 'SRPD51', '5 Sports'),
  ('Seiko', '5 Sports', 'SBSA063', '5 Sports'),
  ('Seiko', 'SKX007', 'SKX007', 'SKX'),
  ('Seiko', 'SKX009', 'SKX009', 'SKX'),
  ('Seiko', 'Alpinist', 'SARB017', 'Alpinist'),
  ('Seiko', 'Alpinist', 'SPB121', 'Alpinist'),
  ('Grand Seiko', 'Snowflake', 'SBGA211', 'Heritage'),
  ('Grand Seiko', 'Snowflake', 'SBGA011', 'Heritage'),
  ('Grand Seiko', '44GS Recreation', 'SBGW253', 'Heritage'),
  ('Grand Seiko', 'Hi-Beat 36000', 'SBGH205', 'Heritage'),
  ('Grand Seiko', 'White Birch', 'SLGH005', 'Evolution 9'),
  ('Grand Seiko', 'Lake Suwa', 'SLGA009', 'Evolution 9'),
  ('Grand Seiko', 'Sport', 'SBGA463', 'Sport'),
  ('Grand Seiko', 'Sport', 'SBGN013', 'Sport'),
  ('Grand Seiko', 'Elegance', 'SBGY007', 'Elegance'),
  ('Grand Seiko', 'Elegance', 'SBGM221', 'Elegance')
) AS v(brand, model, reference, family_name)
JOIN brands b ON b.name_normalized = lower(trim(v.brand))
JOIN watch_families wf ON wf.brand_id = b.id AND wf.name_normalized = lower(trim(v.family_name))
WHERE NOT EXISTS (
  SELECT 1 FROM watches_catalog c
   WHERE c.brand_normalized = lower(trim(v.brand))
     AND c.model_normalized = lower(trim(v.model))
     AND c.reference_normalized = regexp_replace(lower(trim(v.reference)), '[^a-z0-9]+', '', 'g')
);

-- ----- 4. watch_lineage_edges (52) -----
INSERT INTO watch_lineage_edges (predecessor_catalog_id, successor_catalog_id, relationship_type)
SELECT pred.id, succ.id, v.rel_type::lineage_relationship_type
FROM (VALUES
  ('rolex', '5513', 'rolex', '14060m', 'successor', '5513 → 14060 → 14060M no-date Sub chain (1989 transition)'),
  ('rolex', '14060m', 'rolex', '114060', 'successor', '14060M → 114060 (2012 Cerachrom + maxi case)'),
  ('rolex', '114060', 'rolex', '124060', 'successor', '114060 → 124060 (2020 Cal. 3230 redesign)'),
  ('rolex', '16800', 'rolex', '16610', 'successor', '16800 → 16610 (1989 quickset date, sapphire stayed)'),
  ('rolex', '16610', 'rolex', '116610ln', 'successor', '16610 → 116610LN (2010 Cerachrom bezel + maxi case)'),
  ('rolex', '116610ln', 'rolex', '126610ln', 'successor', '116610LN → 126610LN (2020 case redesign, Cal. 3235)'),
  ('rolex', '1665', 'rolex', '16600', 'successor', '1665 → 16600 (modern SD line; 16660 interim 1978-89)'),
  ('rolex', '16600', 'rolex', '116600', 'successor', '16600 → 116600 (2014 maxi case + Cerachrom)'),
  ('rolex', '116600', 'rolex', '126600', 'successor', '116600 → 126600 (2017 to 43mm + Cyclops)'),
  ('rolex', '1675', 'rolex', '16710', 'successor', '1675 → 16710 (1989 GMT II with independent hour hand)'),
  ('rolex', '16710', 'rolex', '116710ln', 'successor', '16710 → 116710LN (2007 Cerachrom black bezel)'),
  ('rolex', '116710ln', 'rolex', '126710blro', 'successor', '116710LN → 126710BLRO (2018 new case + Pepsi return in steel)'),
  ('rolex', '6263', 'rolex', '16520', 'successor', '6263 → 16520 (1988 self-winding Zenith El Primero)'),
  ('rolex', '16520', 'rolex', '116520', 'successor', '16520 → 116520 (2000 in-house Cal. 4130)'),
  ('rolex', '116520', 'rolex', '116500ln', 'successor', '116520 → 116500LN (2016 Cerachrom bezel)'),
  ('rolex', '116500ln', 'rolex', '126500ln', 'successor', '116500LN → 126500LN (2023 Cal. 4131, 60th anniv. refresh)'),
  ('rolex', '214270', 'rolex', '124270', 'successor', '214270 → 124270 (2021 back to 36mm, Cal. 3230)'),
  ('rolex', '116234', 'rolex', '126234', 'successor', '116234 → 126234 (2018 Cal. 3235 update)'),
  ('omega', 'ck2998', 'omega', '105-012', 'successor', 'CK2998 → 105.012 (1965 "Professional" dial; 105.002/.003 interim)'),
  ('omega', '105-012', 'omega', '145-012', 'successor', '105.012 → 145.012 (1967 minor update, Cal. 321)'),
  ('omega', '145-012', 'omega', '145-022', 'successor', '145.012 → 145.022 (1969 transition to Cal. 861)'),
  ('omega', '145-022', 'omega', '3590-50', 'successor', '145.022 → 3590.50 (1988 Cal. 861 → Cal. 1861)'),
  ('omega', '3590-50', 'omega', '3570-50', 'successor', '3590.50 → 3570.50 (1996 ref renumbering)'),
  ('omega', '3570-50', 'omega', '311-30-42-30-01-005', 'successor', '3570.50 → 311.30.42.30.01.005 (2014 modern ref format)'),
  ('omega', '311-30-42-30-01-005', 'omega', '310-30-42-50-01-001', 'successor', '311 → 310 (2021 Cal. 3861 Master Chronometer)'),
  ('omega', '2531-80', 'omega', '212-30-41-20-01-003', 'successor', '2531.80 → 212.30.41.20.01.003 (2012 ceramic bezel + Cal. 8500)'),
  ('omega', '212-30-41-20-01-003', 'omega', '210-30-42-20-01-001', 'successor', '212 → 210 (2018 wave dial, Cal. 8800)'),
  ('omega', '2200-50', 'omega', '215-30-44-21-01-001', 'successor', '2200.50 → 215.30.44.21.01.001 (Cal. 8900 redesign)'),
  ('audemars piguet', '14790st', 'audemars piguet', '15300st', 'successor', '14790ST → 15300ST (2005 to 39mm Cal. 3120)'),
  ('audemars piguet', '15300st', 'audemars piguet', '15400st', 'successor', '15300ST → 15400ST (2012 to 41mm)'),
  ('audemars piguet', '15400st', 'audemars piguet', '15500st', 'successor', '15400ST → 15500ST (2019 refreshed dial, larger date)'),
  ('audemars piguet', '15202st', 'audemars piguet', '16202st', 'successor', '15202ST → 16202ST (2022 end-of-15202 production, Cal. 7121)'),
  ('audemars piguet', '5402st', 'audemars piguet', '15202st', 'remake', '5402ST → 15202ST (2012 faithful 39mm Jumbo reissue, 40th anniv.)'),
  ('audemars piguet', '5402st', 'audemars piguet', '16202st', 'tribute', '5402ST → 16202ST (2022 50th-anniversary nod to original)'),
  ('audemars piguet', '25721st', 'audemars piguet', '26470st', 'successor', '25721ST → 26470ST (2014 modern 42mm ROO Chronograph)'),
  ('audemars piguet', '26470st', 'audemars piguet', '26420so', 'successor', '26470ST → 26420SO (2021 43mm new-case ROO)'),
  ('longines', 'l3-674-4-50-0', 'longines', 'l3-774-4-50-9', 'successor', 'L3.674 → L3.774 (2019 44mm → 42mm Legend Diver variant)'),
  ('seiko', 'skx007', 'seiko', 'srpd51', 'successor', 'SKX007 → SRPD51 (2019 5KX replaced discontinued SKX line)'),
  ('seiko', 'sbdc001', 'seiko', 'spb101', 'successor', 'SBDC001 → SPB101 (2019 redesign + Cal. 6R35)'),
  ('grand seiko', 'sbga011', 'grand seiko', 'sbga211', 'successor', 'SBGA011 → SBGA211 (2017 Snowflake dial refresh + caliber update)'),
  ('seiko', '6217-8001', 'seiko', 'sla017', 'tribute', '6217-8001 → SLA017 (2017 50th-anniversary 62MAS recreation)'),
  ('seiko', '6105-8110', 'seiko', 'sla033', 'tribute', '6105-8110 → SLA033 (2020 "Captain Willard" recreation)'),
  ('seiko', '6309-7040', 'seiko', 'srp777', 'tribute', '6309-7040 → SRP777 (2016 modern Turtle, cushion-case revival)'),
  ('rolex', '5513', 'tudor', '79230n', 'homage', '5513 → Black Bay 79230N (vintage Sub aesthetic, modern Tudor diver)'),
  ('rolex', '5513', 'tudor', '79030n', 'homage', '5513 → BB58 79030N (39mm proportions reference vintage Sub)'),
  ('rolex', '5513', 'squale', '1521-026', 'homage', '5513 → Squale 1521 (period-correct ''70s Sub-style diver)'),
  ('rolex', '5513', 'steinhart', 'ocean-ovm', 'homage', '5513 → Steinhart OVM (MilSub-style military Sub homage)'),
  ('rolex', '16610', 'steinhart', 'ocean-one-39', 'homage', '16610 → Ocean One 39 (famously close modern Sub-clone)'),
  ('rolex', '116610ln', 'christopher ward', 'c60-300', 'homage', '116610LN → C60 Trident (modern ceramic-Sub-style UK micro)'),
  ('omega', '311-30-42-30-01-005', 'swatch', 'so33m100', 'homage', '311 → MoonSwatch Mission to the Moon (Bioceramic Speedy lookalike)'),
  ('omega', '311-30-42-30-01-005', 'swatch', 'so33a100', 'homage', '311 → MoonSwatch Mission to Mars (red-cased Speedy homage)'),
  ('omega', '311-30-42-30-01-005', 'swatch', 'so33g100', 'homage', '311 → MoonSwatch Mission to Earth (brown-dial Speedy homage)')
) AS v(pred_brand_norm, pred_ref_norm, succ_brand_norm, succ_ref_norm, rel_type, note)
JOIN watches_catalog pred ON pred.brand_normalized = v.pred_brand_norm
  AND pred.reference_normalized = regexp_replace(v.pred_ref_norm, '[^a-z0-9]+', '', 'g')
JOIN watches_catalog succ ON succ.brand_normalized = v.succ_brand_norm
  AND succ.reference_normalized = regexp_replace(v.succ_ref_norm, '[^a-z0-9]+', '', 'g')
ON CONFLICT (predecessor_catalog_id, successor_catalog_id, relationship_type) DO NOTHING;

-- ----- summary -----
SELECT
  (SELECT COUNT(*) FROM brands)                AS total_brands,
  (SELECT COUNT(*) FROM watch_families)        AS total_families,
  (SELECT COUNT(*) FROM watches_catalog)       AS total_catalog_rows,
  (SELECT COUNT(*) FROM watches_catalog WHERE family_id IS NOT NULL) AS catalog_with_family,
  (SELECT COUNT(*) FROM watch_lineage_edges)   AS total_lineage_edges;

COMMIT;
