-- Quick task 260620-gk9 — Backfill 18 missing watches_catalog.image_url values
--   + delete rogue brand='test' model='test' row
--
-- PROD-ONLY — do NOT apply locally.
-- Local watches_catalog has known id divergence (project_catalog-id-divergence) and
-- the natural-key UNIQUE constraint is frequently dropped by drizzle-kit pushes
-- (project_local_catalog_natural_key_drift). Apply to prod only.
--
-- Source: scripts/seed-data/catalog-missing-images.md
-- Generated by: npm run catalog:missing-images (prod, 2026-06-20)
-- 19 of 194 rows were missing image_url (9.8%); 18 are backfilled here; 1 test row deleted.
--
-- Apply via: supabase db push --linked
-- Do NOT use: drizzle-kit push / supabase db reset / local psql
-- Per memory: project_drizzle_supabase_db_mismatch
--
-- Idempotency strategy: every UPDATE includes the guard
--   AND (image_url IS NULL OR btrim(image_url) = '')
-- so re-applying this file to prod is a no-op — it will NOT overwrite any URL
-- the operator has changed by hand since the initial apply.
--
-- watches_catalog is non-wipeable per memory project_db_wipeable_2026_05_09 (LLM/factual/
-- photo enrichment investment). This migration uses UPDATE+DELETE only — no schema change.
--
-- All 18 rows are keyed by (brand, model, reference) natural triple — NEVER by id
-- (per project_catalog-id-divergence: local and prod ids diverge).

BEGIN;

-- Pre-flight: assert all 18 target (brand, model, reference) triples exist in prod catalog.
-- If any triple is missing (e.g. hidden trailing space or smart-quote in source markdown),
-- the transaction rolls back before touching any data.
DO $$
DECLARE found int;
BEGIN
  SELECT count(*) INTO found FROM public.watches_catalog
   WHERE (brand, model, reference) IN (
     ('A. Lange & Söhne', '1815', '233.026'),
     ('A. Lange & Söhne', 'Odysseus', '363.179'),
     ('A. Lange & Söhne', 'Saxonia Thin', '211.027'),
     ('Baume & Mercier', 'Riviera', '10728'),
     ('Blancpain', 'Fifty Fathoms', '5015-1130-71S'),
     ('Certina', 'DS Action GMT Powermatic 80', 'C032.929.11.051.00'),
     ('Christopher Ward', 'The Twelve 40mm', 'C12-40A-S00K0-S00B0-K'),
     ('Jaeger-LeCoultre', 'Master Ultra Thin', 'Q1342520'),
     ('Jaeger-LeCoultre', 'Master Ultra Thin Small Seconds', 'Q1218420'),
     ('Jaeger-LeCoultre', 'Polaris Date', 'Q9068681'),
     ('Omega', 'Seamaster 300', '234.30.41.21.03.001'),
     ('Orient', 'Bambino Version 7', 'FAC0000DD0'),
     ('Rolex', 'Datejust 41', '126334'),
     ('Rolex', 'Explorer 40', '224270'),
     ('Sinn', '856 UTC', '856.010'),
     ('Tudor', 'Black Bay 58 GMT', '7939G1A0NRU'),
     ('Vacheron Constantin', 'Overseas', '4500V/110A-B128'),
     ('Zenith', 'Defy Skyline', '03.9300.3620/01.I001')
   );
  IF found <> 18 THEN
    RAISE EXCEPTION 'pre-flight: expected 18 matching catalog rows, found %', found;
  END IF;
END $$;

-- 18 idempotent UPDATE statements — one per missing-image row.
-- Guard: AND (image_url IS NULL OR btrim(image_url) = '') ensures re-apply is a no-op.

UPDATE public.watches_catalog
   SET image_url = 'https://img.alange-soehne.com/product-slideshow-product-md-2/o-dpr-2/dd4f450ea345e51965dc27a803e2ce3bfbf2c3ef.jpg',
       updated_at = now()
 WHERE brand = 'A. Lange & Söhne'
   AND model = '1815'
   AND reference = '233.026'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://img.alange-soehne.com/product-slideshow-product-md-2/o-dpr-2/a61eaa31e3b0c01d8e734fb23685e4a331e4eb42.jpg',
       updated_at = now()
 WHERE brand = 'A. Lange & Söhne'
   AND model = 'Odysseus'
   AND reference = '363.179'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://img.alange-soehne.com/product-light-box-2/o-dpr-2/2baf6e623a66d1bd02e8871be4a07eb99a304dce.jpg',
       updated_at = now()
 WHERE brand = 'A. Lange & Söhne'
   AND model = 'Saxonia Thin'
   AND reference = '211.027'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.baume-et-mercier.com/content/dam/rcq/bem/w1/JA/BK/5v/TE/mC/M8/SZ/zh/ar/Pg/w1JABK5vTEmCM8SZzharPg.png.transform.bemproddetails.png',
       updated_at = now()
 WHERE brand = 'Baume & Mercier'
   AND model = 'Riviera'
   AND reference = '10728'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://prestigedam.swatchgroup.biz/transform/7d970e67-116d-4f36-b1a5-717fab17e6bf/5010_1130_71S_Fifty_Fathoms_Automatique_Soldier_Front_RGB',
       updated_at = now()
 WHERE brand = 'Blancpain'
   AND model = 'Fifty Fathoms'
   AND reference = '5015-1130-71S'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.certina.com/sites/default/files/styles/nocrop_full_lg/public/maps-medias/C032.929.11.051.00_SLD.png?itok=uWnLdN5a',
       updated_at = now()
 WHERE brand = 'Certina'
   AND model = 'DS Action GMT Powermatic 80'
   AND reference = 'C032.929.11.051.00'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.christopherward.com/dw/image/v2/BDWD_PRD/on/demandware.static/-/Sites-cw-master-catalog/default/dw2d4e21be/images/WATCHES/C12-38ADA1-S00B0-B0/C12-38ADA1-S00B0-B0_Picture_1.jpg?sw=2000&sh=2000',
       updated_at = now()
 WHERE brand = 'Christopher Ward'
   AND model = 'The Twelve 40mm'
   AND reference = 'C12-40A-S00K0-S00B0-K'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://img.jaeger-lecoultre.com/product-light-box-1/o-dpr-2/ed2cc7977d257d861c86ff142cda1b26f5172f35.jpg',
       updated_at = now()
 WHERE brand = 'Jaeger-LeCoultre'
   AND model = 'Master Ultra Thin'
   AND reference = 'Q1342520'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://img.jaeger-lecoultre.com/product-light-box-1/o-dpr-2/226152206b915272add4e19bc17251e0fa8ae2d7.jpg',
       updated_at = now()
 WHERE brand = 'Jaeger-LeCoultre'
   AND model = 'Master Ultra Thin Small Seconds'
   AND reference = 'Q1218420'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://img.jaeger-lecoultre.com/product-light-box-1/o-dpr-2/c92af3a2b249b6ad5bf0f4cf607534227e456d2e.jpg',
       updated_at = now()
 WHERE brand = 'Jaeger-LeCoultre'
   AND model = 'Polaris Date'
   AND reference = 'Q9068681'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-300-co-axial-master-chronometer-41-mm-23430412103001-6a0eec.png?w=1100',
       updated_at = now()
 WHERE brand = 'Omega'
   AND model = 'Seamaster 300'
   AND reference = '234.30.41.21.03.001'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://cdn.shopify.com/s/files/1/0026/4978/4385/files/RA-AC0033Y.png?v=1779494235&width=800&height=1000&crop=center',
       updated_at = now()
 WHERE brand = 'Orient'
   AND model = 'Bambino Version 7'
   AND reference = 'FAC0000DD0'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1600/v1/a677b2c664f6/catalogue/2026/upright-c/m126334-0001',
       updated_at = now()
 WHERE brand = 'Rolex'
   AND model = 'Datejust 41'
   AND reference = '126334'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1600/v1/a677b2c664f6/catalogue/2026/upright-c/m224270-0001',
       updated_at = now()
 WHERE brand = 'Rolex'
   AND model = 'Explorer 40'
   AND reference = '224270'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.sinn.de/out/pictures/generated/product/1/1320_2040_100/856.010_400_20_mit_band.png?t=1690905142',
       updated_at = now()
 WHERE brand = 'Sinn'
   AND model = '856 UTC'
   AND reference = '856.010'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch-zoom/c_limit,w_3840/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m7939g1a0nru-0001',
       updated_at = now()
 WHERE brand = 'Tudor'
   AND model = 'Black Bay 58 GMT'
   AND reference = '7939G1A0NRU'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://www.vacheron-constantin.com/dam/rcq/vac/os/Cb/fi/ew/uU/ym/am/PZ/Qu/r_/NQ/osCbfiewuUymamPZQur_NQ.png.transform.vacdetail.png',
       updated_at = now()
 WHERE brand = 'Vacheron Constantin'
   AND model = 'Overseas'
   AND reference = '4500V/110A-B128'
   AND (image_url IS NULL OR btrim(image_url) = '');

UPDATE public.watches_catalog
   SET image_url = 'https://images.zenith-watches.com/asset/5e6cad8c-4364-4ea7-a0cc-50dd12898b11/Digital-RGB/1-SOLDAT-2_DEFY-Skyline_03-9300-3620-01-I001_4x5.png?im=Resize=900',
       updated_at = now()
 WHERE brand = 'Zenith'
   AND model = 'Defy Skyline'
   AND reference = '03.9300.3620/01.I001'
   AND (image_url IS NULL OR btrim(image_url) = '');

-- Defense-in-depth DELETE of the rogue brand='test' model='test' row.
-- Guards: owners_count=0, wishlist_count=0, no watches rows pointing at this catalog entry.
-- This row has 0 owners, 0 wishlist, and was never used — safe to delete.
DELETE FROM public.watches_catalog
 WHERE brand = 'test'
   AND model = 'test'
   AND reference IS NULL
   AND coalesce(owners_count, 0) = 0
   AND coalesce(wishlist_count, 0) = 0
   AND NOT EXISTS (
     SELECT 1 FROM public.watches w WHERE w.catalog_id = watches_catalog.id
   );

-- Post-flight: confirm no targeted row is still missing an image_url,
-- and confirm the test/test row is gone.
DO $$
DECLARE still_missing int;
DECLARE test_row int;
BEGIN
  SELECT count(*) INTO still_missing FROM public.watches_catalog
   WHERE (brand, model, reference) IN (
     ('A. Lange & Söhne', '1815', '233.026'),
     ('A. Lange & Söhne', 'Odysseus', '363.179'),
     ('A. Lange & Söhne', 'Saxonia Thin', '211.027'),
     ('Baume & Mercier', 'Riviera', '10728'),
     ('Blancpain', 'Fifty Fathoms', '5015-1130-71S'),
     ('Certina', 'DS Action GMT Powermatic 80', 'C032.929.11.051.00'),
     ('Christopher Ward', 'The Twelve 40mm', 'C12-40A-S00K0-S00B0-K'),
     ('Jaeger-LeCoultre', 'Master Ultra Thin', 'Q1342520'),
     ('Jaeger-LeCoultre', 'Master Ultra Thin Small Seconds', 'Q1218420'),
     ('Jaeger-LeCoultre', 'Polaris Date', 'Q9068681'),
     ('Omega', 'Seamaster 300', '234.30.41.21.03.001'),
     ('Orient', 'Bambino Version 7', 'FAC0000DD0'),
     ('Rolex', 'Datejust 41', '126334'),
     ('Rolex', 'Explorer 40', '224270'),
     ('Sinn', '856 UTC', '856.010'),
     ('Tudor', 'Black Bay 58 GMT', '7939G1A0NRU'),
     ('Vacheron Constantin', 'Overseas', '4500V/110A-B128'),
     ('Zenith', 'Defy Skyline', '03.9300.3620/01.I001')
   )
     AND (image_url IS NULL OR btrim(image_url) = '');
  IF still_missing > 0 THEN
    RAISE EXCEPTION 'post-flight: % of the 18 targeted rows still missing image_url', still_missing;
  END IF;

  SELECT count(*) INTO test_row FROM public.watches_catalog
   WHERE brand = 'test' AND model = 'test' AND reference IS NULL;
  IF test_row <> 0 THEN
    RAISE EXCEPTION 'post-flight: test/test row was not deleted (count=%)', test_row;
  END IF;
END $$;

COMMIT;
