-- Phase 44 data migration: taste attributes backfill.
-- Generated by: npm run db:backfill-taste (local run)
-- Source: Phase 44 CONTEXT.md D-14
-- Apply: supabase db push --linked (never drizzle-kit push for prod)
-- Idempotent: each UPDATE is WHERE id = '<uuid>' — re-running is a no-op on already-updated rows.
-- Rows: 101
BEGIN;
UPDATE watches_catalog SET
  formality            = 0.5,
  sportiness           = 0.5,
  heritage_score       = 0.1,
  primary_archetype    = 'hybrid',
  era_signal           = 'contemporary',
  design_motifs        = '{}'::text[],
  confidence           = 0.05,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '00000000-0000-4000-a000-000000000037';

UPDATE watches_catalog SET
  formality            = 0.78,
  sportiness           = 0.15,
  heritage_score       = 0.92,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','dressy-bezel','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '02a01e2b-acf3-4b1a-a1e4-76e7e16e58d6';

UPDATE watches_catalog SET
  formality            = 0.62,
  sportiness           = 0.38,
  heritage_score       = 0.78,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.91,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '09120249-c053-4b42-89b7-252d5db90ddb';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.82,
  heritage_score       = 0.92,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','guilloche-dial','textured-dial','dressy-bezel']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '0b0eb71b-8e1d-4029-a5f1-01267408ad2a';

UPDATE watches_catalog SET
  formality            = 0.72,
  sportiness           = 0.25,
  heritage_score       = 0.92,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','dressy-bezel','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '0f655636-8c54-4ae7-a0ce-00c535782b56';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.82,
  heritage_score       = 0.78,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','tropic-strap','domed-crystal','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '16cb2412-eb6d-41e1-8414-b89be87aa53c';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.85,
  heritage_score       = 0.35,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','textured-dial','dressy-bezel']::text[],
  confidence           = 0.72,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '172c07a1-2da4-4c7d-b414-da376b414b50';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.88,
  heritage_score       = 0.97,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','applied-indices','mercedes-hands','domed-crystal','patina-friendly','exhibition-caseback']::text[],
  confidence           = 0.91,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '173ef234-1a5c-4781-bd58-cd6d40c27811';

UPDATE watches_catalog SET
  formality            = 0.88,
  sportiness           = 0.05,
  heritage_score       = 0.95,
  primary_archetype    = 'dress',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '1c0ed27b-ecdf-4ad8-a856-68943f2fc38b';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.7,
  heritage_score       = 0.65,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['asymmetric-case','textured-dial','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.62,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '1e7aed78-9d7c-4bb0-bae1-ff97e6a3440b';

UPDATE watches_catalog SET
  formality            = 0.42,
  sportiness           = 0.72,
  heritage_score       = 0.88,
  primary_archetype    = 'gmt',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '2141ed12-8b6e-4691-9917-55076bd64dfd';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.45,
  heritage_score       = 0.82,
  primary_archetype    = 'field',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','patina-friendly','domed-crystal']::text[],
  confidence           = 0.8,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '21be342c-f466-48b9-999a-22295c6cfda9';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.72,
  heritage_score       = 0.98,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','exhibition-caseback','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '22dc3111-3e87-45e0-892a-69bc53d59298';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.55,
  heritage_score       = 0.72,
  primary_archetype    = 'pilot',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','bauhaus']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '25d5493a-6971-496e-8600-f57219a677a5';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.85,
  heritage_score       = 0.7,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','textured-dial','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '270b9f8e-11a6-4868-b02c-a4c5f2c0230f';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.82,
  heritage_score       = 0.85,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','exhibition-caseback','dressy-bezel','compressor-case']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '287c8aca-4f2d-4076-b598-f011c0e26d25';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.62,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '2cd72016-d9d8-4316-80be-6bfedddca723';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','domed-crystal','exhibition-caseback','textured-dial']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '3704716f-9d5d-4e09-a337-c7bfe81d7d31';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.82,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['patina-friendly','domed-crystal','applied-indices','textured-dial']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '3935ab19-2d72-40f6-961b-e363cc92f51a';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.82,
  heritage_score       = 0.97,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['gilt-dial','applied-indices','mercedes-hands','domed-crystal','patina-friendly','textured-dial']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '3cd1a7eb-72fc-41fe-8d32-d321b8c1417a';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.6,
  heritage_score       = 0.95,
  primary_archetype    = 'gmt',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['gilt-dial','mercedes-hands','applied-indices','domed-crystal','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '400be415-74c7-477a-85e4-8b7d6ba870a2';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.72,
  heritage_score       = 0.97,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','textured-dial','domed-crystal','exhibition-caseback','patina-friendly','tropic-strap']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '46799878-e3ed-42ed-874e-4472533e3247';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.75,
  heritage_score       = 0.97,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','asymmetric-case','patina-friendly','domed-crystal','textured-dial']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '4c006762-b03d-42fe-a4a1-7dbea4cea8ac';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['asymmetric-case','cushion-case','textured-dial','applied-indices','patina-friendly','domed-crystal']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '4c7c6942-981c-4579-b7f9-72c2e5ef2df8';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.82,
  heritage_score       = 0.65,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','syringe-hands','exhibition-caseback']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '4d67cbfa-9f17-44c5-97d0-9abab206c9a0';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.82,
  heritage_score       = 0.97,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','patina-friendly','textured-dial','exhibition-caseback']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '4d8d045d-1065-4767-a95c-3f1c8809a440';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.72,
  heritage_score       = 0.95,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','dressy-bezel','textured-dial','exhibition-caseback']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '501bb888-4abd-419c-80a0-f754b113e9cb';

UPDATE watches_catalog SET
  formality            = 0.88,
  sportiness           = 0.05,
  heritage_score       = 0.72,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '53d2266b-181c-4216-a1a0-c21cf5a965a2';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.82,
  heritage_score       = 0.92,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel','patina-friendly']::text[],
  confidence           = 0.91,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '5477686b-944c-4352-8df8-688017a08bcb';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.55,
  heritage_score       = 0.82,
  primary_archetype    = 'field',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','cathedral-hands','gilt-dial','textured-dial','dressy-bezel','patina-friendly']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '5ecf013c-229a-4faa-b80f-4295e9f20772';

UPDATE watches_catalog SET
  formality            = 0.72,
  sportiness           = 0.2,
  heritage_score       = 0.78,
  primary_archetype    = 'gmt',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','domed-crystal','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '6152be35-65a2-4708-a940-2474e38e6233';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.55,
  heritage_score       = 0.72,
  primary_archetype    = 'sport',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback']::text[],
  confidence           = 0.72,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '62ac657c-2557-48d4-959e-254f456d6006';

UPDATE watches_catalog SET
  formality            = 0.72,
  sportiness           = 0.3,
  heritage_score       = 0.97,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel','domed-crystal']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '66281f45-cfab-43ec-884a-3917de78b00e';

UPDATE watches_catalog SET
  formality            = 0.28,
  sportiness           = 0.72,
  heritage_score       = 0.82,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','compressor-case','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '68a8ef36-07a3-4004-9463-289e04c12eec';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.88,
  heritage_score       = 0.88,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['cushion-case','textured-dial','mercedes-hands','patina-friendly','tropic-strap']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '6a608de1-c50a-4169-bdd9-d4a767e2a1a2';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.92,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','textured-dial','domed-crystal','tropic-strap','patina-friendly']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '6cff3235-d773-442e-952a-dc538001ff82';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.85,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','applied-indices','syringe-hands','exhibition-caseback','integrated-bracelet','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '6d24e088-14f4-4c37-8ea9-dcd3b53526ab';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','patina-friendly','cushion-case','textured-dial']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '7c6852ab-25e6-493e-8f92-0ed8263d3d94';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.88,
  heritage_score       = 0.42,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '7d57991b-3871-4909-9f58-73b7be72e45a';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.82,
  primary_archetype    = 'dive',
  era_signal           = 'modern',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','dressy-bezel','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '7e389e8c-fa1d-436e-baf4-4e1c3d16e1b6';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.82,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','integrated-bracelet','exhibition-caseback']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '7f5d9bc5-76b4-4612-9e5b-93bbe0082a2c';

UPDATE watches_catalog SET
  formality            = 0.75,
  sportiness           = 0.15,
  heritage_score       = 0.8,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','domed-crystal','exhibition-caseback','dressy-bezel','textured-dial']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '81d3fc52-0f9d-4543-8ce2-5adc62f26b00';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.88,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','textured-dial','domed-crystal','exhibition-caseback']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '83251af2-afe8-438e-8871-d4cd5bcb6ab4';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.82,
  heritage_score       = 0.45,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','integrated-bracelet']::text[],
  confidence           = 0.78,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '83c0396b-3903-40e4-8109-33a2e076b31c';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.8,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'modern',
  design_motifs        = ARRAY['applied-indices','mercedes-hands']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '84d43d0f-b1b4-4243-95b6-4108d34a9036';

UPDATE watches_catalog SET
  formality            = 0.62,
  sportiness           = 0.55,
  heritage_score       = 0.92,
  primary_archetype    = 'sport',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '85cb5e87-6d1d-4ce8-8641-07c035563707';

UPDATE watches_catalog SET
  formality            = 0.72,
  sportiness           = 0.2,
  heritage_score       = 0.82,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','exhibition-caseback','domed-crystal']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '86285bfd-3e01-438a-ba13-d9e1a7a08962';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.85,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','exhibition-caseback','textured-dial']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '86c1937d-27c1-475d-b498-a77c023df697';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.97,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','domed-crystal','patina-friendly','exhibition-caseback']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '8775aebd-4112-41f0-9f77-d81eddc15627';

UPDATE watches_catalog SET
  formality            = 0.82,
  sportiness           = 0.08,
  heritage_score       = 0.92,
  primary_archetype    = 'dress',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['gilt-dial','applied-indices','domed-crystal','exhibition-caseback','dressy-bezel','patina-friendly','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '879e33fa-53ac-4efe-9fba-2c0ba5eee2ec';

UPDATE watches_catalog SET
  formality            = 0.72,
  sportiness           = 0.28,
  heritage_score       = 0.97,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '87e73554-2fde-4406-8a91-870b2b975f37';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.65,
  heritage_score       = 0.95,
  primary_archetype    = 'field',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['mercedes-hands','applied-indices','domed-crystal','patina-friendly']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '87f24038-6073-4f1f-81ba-04dea8f2ff4d';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.72,
  heritage_score       = 0.78,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['asymmetric-case','textured-dial','dressy-bezel','applied-indices']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '8cd60d5d-9d11-453a-8e22-ef8348f4dbea';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.65,
  heritage_score       = 0.7,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['asymmetric-case','textured-dial','dressy-bezel','applied-indices']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '8f065dfc-8e96-4a4b-9ee2-b99013aa067a';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.72,
  heritage_score       = 0.98,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['asymmetric-case','textured-dial','applied-indices','domed-crystal','exhibition-caseback','patina-friendly']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9167a0ac-c80b-4f6e-9656-4ca594e27e17';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.55,
  heritage_score       = 0.75,
  primary_archetype    = 'gmt',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','dressy-bezel','integrated-bracelet','exhibition-caseback']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9402389b-0f01-4aa4-86a9-1f21b6d3dbac';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.88,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','textured-dial','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '948ef89c-2f4e-47c7-9726-5126fe5647a4';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.72,
  heritage_score       = 0.78,
  primary_archetype    = 'gmt',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','mercedes-hands','patina-friendly','beads-of-rice-bracelet','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '95fadf1a-89f4-419b-b7f7-8597f4862d6b';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.75,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '98d97c20-f942-4b92-a09b-a20cd7da55b5';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.82,
  heritage_score       = 0.85,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','domed-crystal','patina-friendly','beads-of-rice-bracelet','dressy-bezel','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9a930356-a8bb-4c3f-83b6-be20c25e6d6f';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.78,
  heritage_score       = 0.92,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','textured-dial','dressy-bezel']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9bc6ccbe-adec-4d3f-b86f-c6fafb67ef79';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.72,
  heritage_score       = 0.88,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['gilt-dial','applied-indices','domed-crystal','patina-friendly','beads-of-rice-bracelet']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9c58f983-23d4-4714-980b-adb9b29744a8';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.78,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['cushion-case','applied-indices','textured-dial','patina-friendly']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9e74f1fa-bbb5-4944-b238-80682be2fdfd';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.75,
  heritage_score       = 0.95,
  primary_archetype    = 'racing',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','textured-dial','exhibition-caseback','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9ea4fd5c-8519-4c13-8a47-b1e1a7e14c3d';

UPDATE watches_catalog SET
  formality            = 0.4,
  sportiness           = 0.65,
  heritage_score       = 0.98,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['asymmetric-case','textured-dial','applied-indices','domed-crystal','patina-friendly','dressy-bezel']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = '9f40982f-10d4-4c56-a516-85bc619bb7be';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.82,
  heritage_score       = 0.3,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','exhibition-caseback']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a1e2fae2-ea0a-400d-89fc-13594bf5fe9a';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.72,
  heritage_score       = 0.72,
  primary_archetype    = 'gmt',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','mercedes-hands','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.85,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a1fe0929-b51f-434b-a0ae-c1e24ade1b64';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.82,
  heritage_score       = 0.42,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.72,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a427830d-5740-492b-8d4a-281648b9848c';

UPDATE watches_catalog SET
  formality            = 0.55,
  sportiness           = 0.55,
  heritage_score       = 0.97,
  primary_archetype    = 'sport',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.9,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a4d9b4fc-81c8-4c80-b675-e44ffd7d041d';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.85,
  heritage_score       = 0.8,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['cushion-case','textured-dial','applied-indices','patina-friendly']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a5cc76dc-934a-45a5-bac0-9e94818de62a';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.82,
  heritage_score       = 0.9,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','domed-crystal','exhibition-caseback','patina-friendly','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a6284c5d-11c1-487f-a651-493e1428687b';

UPDATE watches_catalog SET
  formality            = 0.55,
  sportiness           = 0.6,
  heritage_score       = 0.9,
  primary_archetype    = 'gmt',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','dressy-bezel','integrated-bracelet','exhibition-caseback']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a6ff6a4d-613b-4b16-940a-d36a38a6f0e4';

UPDATE watches_catalog SET
  formality            = 0.62,
  sportiness           = 0.28,
  heritage_score       = 0.82,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','domed-crystal','exhibition-caseback','integrated-bracelet']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'a8ba5b46-06d6-49da-ad96-9498d65b508a';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','exhibition-caseback','textured-dial']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'aa4a114b-54ce-459c-8dfb-840a98a1e5af';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.6,
  heritage_score       = 0.92,
  primary_archetype    = 'sport',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'aacf5930-32a6-4f80-83b0-83ed2806d205';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.88,
  heritage_score       = 0.9,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['cushion-case','textured-dial','applied-indices','domed-crystal','dressy-bezel','exhibition-caseback','patina-friendly']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'af1bcf54-d6bd-4313-96cd-fa84ec3064b1';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.78,
  heritage_score       = 0.97,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['sector-dial','applied-indices','textured-dial','patina-friendly','domed-crystal','dressy-bezel']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'b04e9e65-4e4b-4aed-bff7-d9b63dd2b559';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.82,
  heritage_score       = 0.8,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['compressor-case','patina-friendly','textured-dial','domed-crystal','tropic-strap']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'ba4fb5a4-e42d-449b-b5b9-899d96d30c42';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.72,
  heritage_score       = 0.97,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','patina-friendly','domed-crystal','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'bb356f1e-3b64-411a-b1b9-adce026af3e7';

UPDATE watches_catalog SET
  formality            = 0.4,
  sportiness           = 0.65,
  heritage_score       = 0.85,
  primary_archetype    = 'field',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','cathedral-hands','exhibition-caseback','domed-crystal','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'bef1ea69-7b14-4c97-849d-a126d203f290';

UPDATE watches_catalog SET
  formality            = 0.55,
  sportiness           = 0.3,
  heritage_score       = 0.82,
  primary_archetype    = 'dress',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','exhibition-caseback','integrated-bracelet','domed-crystal']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'bf99184c-d0b1-4da9-844e-71e6cf45d09f';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.72,
  heritage_score       = 0.72,
  primary_archetype    = 'sport',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','exhibition-caseback','beads-of-rice-bracelet','textured-dial','dressy-bezel']::text[],
  confidence           = 0.8,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c2e7edac-717f-4027-8282-04b9aa753600';

UPDATE watches_catalog SET
  formality            = 0.2,
  sportiness           = 0.85,
  heritage_score       = 0.88,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','textured-dial','exhibition-caseback']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c55d7391-6b33-49e1-95d2-afb9d0b6ffcb';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.82,
  heritage_score       = 0.78,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','exhibition-caseback','dressy-bezel','integrated-bracelet']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c5a89ff1-3569-46fc-a0bb-94728b1fff82';

UPDATE watches_catalog SET
  formality            = 0.15,
  sportiness           = 0.88,
  heritage_score       = 0.88,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','textured-dial','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.91,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c6ccb57a-87ec-49f6-9ca1-a1c2625e19b3';

UPDATE watches_catalog SET
  formality            = 0.42,
  sportiness           = 0.58,
  heritage_score       = 0.88,
  primary_archetype    = 'field',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','bauhaus']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c7f54bfb-b2fa-4006-a8ee-e9a4162acf75';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.6,
  heritage_score       = 0.72,
  primary_archetype    = 'pilot',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','textured-dial','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c86b61c6-b785-46d0-aec8-d67eea7e462f';

UPDATE watches_catalog SET
  formality            = 0.3,
  sportiness           = 0.78,
  heritage_score       = 0.82,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','domed-crystal','textured-dial','dressy-bezel','exhibition-caseback','beads-of-rice-bracelet']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'c9892ccd-ae8e-4f04-af92-cb8e351d58f2';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.75,
  heritage_score       = 0.99,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['asymmetric-case','applied-indices','textured-dial','sector-dial','patina-friendly','domed-crystal']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'cfbc3502-aac9-404c-bd20-35b5493119c2';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.92,
  heritage_score       = 0.82,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','textured-dial','domed-crystal','dressy-bezel','patina-friendly']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'd6fd37cb-f74b-490f-9dd6-7f7813059e4b';

UPDATE watches_catalog SET
  formality            = 0.55,
  sportiness           = 0.72,
  heritage_score       = 0.92,
  primary_archetype    = 'chrono',
  era_signal           = 'modern',
  design_motifs        = ARRAY['applied-indices','textured-dial','dressy-bezel']::text[],
  confidence           = 0.9,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'df751c49-2692-4e75-9aee-0ae51539d52a';

UPDATE watches_catalog SET
  formality            = 0.45,
  sportiness           = 0.55,
  heritage_score       = 1,
  primary_archetype    = 'sport',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','integrated-bracelet','applied-indices','dressy-bezel','patina-friendly']::text[],
  confidence           = 0.95,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'df886285-0a4f-4ddf-9213-28206d7b6742';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.72,
  heritage_score       = 0.97,
  primary_archetype    = 'chrono',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','domed-crystal','patina-friendly','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'e212e65d-3f20-441e-ae88-d8581003532e';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.72,
  heritage_score       = 0.92,
  primary_archetype    = 'gmt',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','patina-friendly','domed-crystal','exhibition-caseback','textured-dial']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'e26c0190-6fda-4785-af21-9cd13b6978eb';

UPDATE watches_catalog SET
  formality            = 0.42,
  sportiness           = 0.82,
  heritage_score       = 0.82,
  primary_archetype    = 'chrono',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'e930edf4-4241-494d-bb08-405deb660ddb';

UPDATE watches_catalog SET
  formality            = 0.55,
  sportiness           = 0.65,
  heritage_score       = 0.95,
  primary_archetype    = 'sport',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['textured-dial','applied-indices','integrated-bracelet','exhibition-caseback','dressy-bezel']::text[],
  confidence           = 0.92,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'ee19092e-3854-43f4-be13-d10b1f6c383e';

UPDATE watches_catalog SET
  formality            = 0.35,
  sportiness           = 0.65,
  heritage_score       = 0.92,
  primary_archetype    = 'field',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','bauhaus','exhibition-caseback']::text[],
  confidence           = 0.9,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'f4d50aec-b6c3-4bbd-aee9-72cd1a5cd146';

UPDATE watches_catalog SET
  formality            = 0.1,
  sportiness           = 0.92,
  heritage_score       = 0.72,
  primary_archetype    = 'dive',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','textured-dial','exhibition-caseback','integrated-bracelet']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'f8c1596d-eb33-49b4-87cd-e5d9b037a7f0';

UPDATE watches_catalog SET
  formality            = 0.25,
  sportiness           = 0.55,
  heritage_score       = 0.88,
  primary_archetype    = 'field',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['textured-dial','applied-indices','patina-friendly','dressy-bezel','domed-crystal']::text[],
  confidence           = 0.82,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'f9ced537-29f6-4499-9407-1da90dbb87d5';

UPDATE watches_catalog SET
  formality            = 0.22,
  sportiness           = 0.82,
  heritage_score       = 0.95,
  primary_archetype    = 'dive',
  era_signal           = 'vintage-leaning',
  design_motifs        = ARRAY['mercedes-hands','applied-indices','textured-dial','patina-friendly']::text[],
  confidence           = 0.88,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'fc984342-be8b-459d-a810-287280ce9033';

UPDATE watches_catalog SET
  formality            = 0.4,
  sportiness           = 0.72,
  heritage_score       = 0.92,
  primary_archetype    = 'gmt',
  era_signal           = 'contemporary',
  design_motifs        = ARRAY['applied-indices','mercedes-hands','dressy-bezel','exhibition-caseback']::text[],
  confidence           = 0.93,
  extracted_from_photo = false,
  updated_at           = now()
WHERE id = 'fecc36c6-0e70-48af-b5b4-d80855307c44';
COMMIT;
