-- Phase 44 data migration: factual attributes backfill.
-- Generated by: npm run db:factual-apply (local run)
-- Source: Phase 44 CONTEXT.md D-14
-- Apply: supabase db push --linked (never drizzle-kit push for prod)
-- Idempotent: each UPDATE is WHERE id = '<uuid>' — re-running is a no-op on already-updated rows.
-- Rows: 101 (404 field updates)
BEGIN;

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['sport', 'dress', 'luxury-sport']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2017/07/AudmarsPiget-5D3_0397.jpg',
  updated_at = now()
WHERE id = 'ee19092e-3854-43f4-be13-d10b1f6c383e';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['sport', 'dress', 'luxury-sport', 'integrated-bracelet']::text[],
  image_url = 'https://cdn.swisswatchexpo.com/productphotos/12/28/audemars-piguet-royal-oak-jumbo-a-series-black-dial-steel-mens-watch-5402st-66829_ad7fd_md.jpg',
  updated_at = now()
WHERE id = 'df886285-0a4f-4ddf-9213-28206d7b6742';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 36,
  style_tags = ARRAY['sport', 'dress', 'luxury-sport']::text[],
  image_url = 'https://cdn.swisswatchexpo.com/productphotos/5/4/audemars-piguet-royal-oak-black-dial-steel-mens-watch-14790st-box-papers-51561_9a00be7fef_md.jpg',
  updated_at = now()
WHERE id = 'a4d9b4fc-81c8-4c80-b675-e44ffd7d041d';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['sport', 'dress', 'luxury-sport', 'integrated-bracelet']::text[],
  image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-598?size=716,0&fmt=avif-alpha&dpr=off',
  updated_at = now()
WHERE id = '85cb5e87-6d1d-4ce8-8641-07c035563707';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['sport', 'dress', 'luxury sport']::text[],
  image_url = 'https://www.acollectedman.com/cdn/shop/products/Audemars_Piguet_Royal_Oak_15300ST_Stainless_Steel_A_Collected_Man_London_WSS_A1315_09_2160x.jpg?v=1666367510',
  updated_at = now()
WHERE id = 'aacf5930-32a6-4f80-83b0-83ed2806d205';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dress', 'sport', 'luxury']::text[],
  image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-880?size=716,0&fmt=avif-alpha&dpr=off',
  updated_at = now()
WHERE id = '87e73554-2fde-4406-8a91-870b2b975f37';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dress', 'sport', 'luxury']::text[],
  image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-157?size=716,0&fmt=avif-alpha&dpr=off',
  updated_at = now()
WHERE id = '66281f45-cfab-43ec-884a-3917de78b00e';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono', 'luxury', 'dress']::text[],
  image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-483?size=716,0&fmt=avif-alpha&dpr=off',
  updated_at = now()
WHERE id = 'e930edf4-4241-494d-bb08-405deb660ddb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 43,
  style_tags = ARRAY['sport', 'chrono', 'luxury-sport']::text[],
  image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-1068?size=716,0&fmt=avif-alpha&dpr=off',
  updated_at = now()
WHERE id = '287c8aca-4f2d-4076-b598-f011c0e26d25';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono', 'luxury-sport']::text[],
  image_url = 'https://monochrome-watches.com/app/uploads/2022/12/Collector-Guide-First-Generation-Audemars-Piguet-Royal-Oak-Offshore-25721ST-23.jpg',
  updated_at = now()
WHERE id = '5477686b-944c-4352-8df8-688017a08bcb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 38,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://static.wixstatic.com/media/7ee37d_d8f27833bbbb4677b1c58e8d4980af73~mv2.webp/v1/fill/w_1526,h_1018,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/7ee37d_d8f27833bbbb4677b1c58e8d4980af73~mv2.webp',
  updated_at = now()
WHERE id = '172c07a1-2da4-4c7d-b414-da376b414b50';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.christopherward.com/dw/image/v2/BDWD_PRD/on/demandware.static/-/Sites-cw-master-catalog/default/dw77871930/images/WATCHES/C60-40ADA31S0KK1-B0/C60-40ADA31S0KK1-B0_Picture_2.jpg?sw=2000&sh=2000',
  updated_at = now()
WHERE id = '7d57991b-3871-4909-9f58-73b7be72e45a';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 38,
  style_tags = ARRAY['dress']::text[],
  image_url = 'https://substackcdn.com/image/fetch/$s_!KM2w!,w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F120d18b0-f1ee-43e4-9486-b6d5382c927e_500x423.jpeg',
  updated_at = now()
WHERE id = '1c0ed27b-ecdf-4ad8-a856-68943f2fc38b';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39.5,
  style_tags = ARRAY['dress', 'gmt', 'sport']::text[],
  image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGM221/SBGM221_dial.jpg',
  updated_at = now()
WHERE id = '6152be35-65a2-4708-a940-2474e38e6233';

UPDATE watches_catalog SET
  movement_type = 'spring_drive',
  case_size_mm = 38.5,
  style_tags = ARRAY['dress', 'elegance']::text[],
  image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGY007/SBGY007_dial.jpg?mh=1200&mw=1200&hash=E2B13B85D80435AEAAC1E8A90C57B188',
  updated_at = now()
WHERE id = '53d2266b-181c-4216-a1a0-c21cf5a965a2';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40.2,
  style_tags = ARRAY['dress', 'sport', 'heritage']::text[],
  image_url = 'https://www.grand-seiko.com/uk-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/22/00/SBGH205G/SBGH205G.png',
  updated_at = now()
WHERE id = '86285bfd-3e01-438a-ba13-d9e1a7a08962';

UPDATE watches_catalog SET
  movement_type = 'spring_drive',
  case_size_mm = 40,
  style_tags = ARRAY['sport', 'dress']::text[],
  image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/23/13/SLGA009G/SLGA009G.png',
  updated_at = now()
WHERE id = '62ac657c-2557-48d4-959e-254f456d6006';

UPDATE watches_catalog SET
  movement_type = 'spring_drive',
  case_size_mm = 41,
  style_tags = ARRAY['dress', 'sport', 'heritage']::text[],
  image_url = 'https://grandseikoboutique.us/cdn/shop/files/SBGA211-grand-seiko-watch-spring-drive-snowflake.png?v=1774888667',
  updated_at = now()
WHERE id = 'a8ba5b46-06d6-49da-ad96-9498d65b508a';

UPDATE watches_catalog SET
  movement_type = 'spring_drive',
  case_size_mm = 41,
  style_tags = ARRAY['dress', 'sport']::text[],
  image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGA211/SBGA211_dial.jpg',
  updated_at = now()
WHERE id = 'bf99184c-d0b1-4da9-844e-71e6cf45d09f';

UPDATE watches_catalog SET
  movement_type = 'spring_drive',
  case_size_mm = 44.2,
  style_tags = ARRAY['sport', 'dive']::text[],
  image_url = 'https://grandseikoboutique.us/cdn/shop/products/Grand-Seiko-SBGA463-spring-drive-watch.png?v=1636490448&width=1200',
  updated_at = now()
WHERE id = '7f5d9bc5-76b4-4612-9e5b-93bbe0082a2c';

UPDATE watches_catalog SET
  movement_type = 'quartz',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'dress', 'travel']::text[],
  image_url = 'https://images.ctfassets.net/517dkfc553yf/6jomZ0f9BPSGKreoAco2PT/94f2e19249c5486c4f18f0ad084d6739/SBGN013.jpg?w=1280&h=1398&fm=webp',
  updated_at = now()
WHERE id = '9402389b-0f01-4aa4-86a9-1f21b6d3dbac';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dress', 'sport']::text[],
  image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/23/14/SLGH005G/SLGH005G.png',
  updated_at = now()
WHERE id = '09120249-c053-4b42-89b7-252d5db90ddb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['field', 'military', 'dress', 'sport']::text[],
  image_url = 'https://s.turbifycdn.com/aah/movadobaby/longines-heritage-military-1938-l2-788-4-53-0-67.jpg',
  updated_at = now()
WHERE id = '21be342c-f466-48b9-999a-22295c6cfda9';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['field', 'military', 'dress', 'sport']::text[],
  image_url = 'https://cdn.watchbase.com/watch/lg/origin:png/longines/heritage/l28324530-2f.webp',
  updated_at = now()
WHERE id = 'f9ced537-29f6-4499-9407-1da90dbb87d5';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-781-4-06-6-2799e4-hero.png?w=1920',
  updated_at = now()
WHERE id = '83c0396b-3903-40e4-8109-33a2e076b31c';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-781-4-96-6-ddea24-hero.png?w=1920',
  updated_at = now()
WHERE id = 'a427830d-5740-492b-8d4a-281648b9848c';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport', 'heritage']::text[],
  image_url = 'https://www.thetimepiececollection.com/media/catalog/product/cache/8060fbcc986bd45c6a23957550dd7450/l/3/l3.774.4.50.9_1_1__nempwe4jhc2q9hed.jpg',
  updated_at = now()
WHERE id = '68a8ef36-07a3-4004-9463-289e04c12eec';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport', 'heritage']::text[],
  image_url = 'https://cdn.watchbase.com/watch/lg/origin:jpg/longines/heritage/l36744500-38.webp',
  updated_at = now()
WHERE id = 'ba4fb5a4-e42d-449b-b5b9-899d96d30c42';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['pilot', 'sport', 'field', 'dress']::text[],
  image_url = 'https://cdn.watchtime.com/watchtime_en-us/2020/06/Longines_Spirit_mattblack_front_1000_640.webp',
  updated_at = now()
WHERE id = '25d5493a-6971-496e-8600-f57219a677a5';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['pilot', 'gmt', 'sport', 'field']::text[],
  image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-spirit-zulu-time-l3-812-4-63-6-3ffc56-hero.png?w=1920',
  updated_at = now()
WHERE id = 'c86b61c6-b785-46d0-aec8-d67eea7e462f';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 34,
  style_tags = ARRAY['dress', 'vintage']::text[],
  image_url = 'https://img.everywatch.com/media/2024/01/02/omega-constellation-168-00510470216.webp',
  updated_at = now()
WHERE id = '879e33fa-53ac-4efe-9fba-2c0ba5eee2ec';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dress', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-constellation-globemaster-co-axial-master-chronometer-39-mm-13033392102001-b7c8cb.png?w=1100',
  updated_at = now()
WHERE id = '81d3fc52-0f9d-4543-8ce2-5adc62f26b00';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-300-m-chronometer-25318000-dc7fae.png?w=1100',
  updated_at = now()
WHERE id = '6d24e088-14f4-4c37-8ea9-dcd3b53526ab';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-diver-300m-co-axial-master-chronometer-42-mm-21030422001001-23ffb2.png?w=1100',
  updated_at = now()
WHERE id = 'c5a89ff1-3569-46fc-a0bb-94728b1fff82';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-diver-300m-co-axial-chronometer-41-mm-21230412001003-bfcfd9.png?w=1100',
  updated_at = now()
WHERE id = '7e389e8c-fa1d-436e-baf4-4e1c3d16e1b6';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45.5,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-planet-ocean-big-size-22005000-272076.png?w=1100',
  updated_at = now()
WHERE id = '3704716f-9d5d-4e09-a337-c7bfe81d7d31';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 43.5,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-planet-ocean-600m-co-axial-master-chronometer-43-5-mm-21530442101001-8e6904.png?w=1100',
  updated_at = now()
WHERE id = '270b9f8e-11a6-4868-b02c-a4c5f2c0230f';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 39.7,
  style_tags = ARRAY['chrono', 'sport', 'heritage', 'dress']::text[],
  image_url = 'https://img.watchcrunch.com/rgpqmGDK7BQZf3sojdEIk1CbLNVcYZvPZcE0TxPgCAA/w:4096/h:320/rt:fit/g:sm/dpr:2/aW1nOi8vMjAyNS8wMi8xMi9yZmhEUHhmZFBlR05QTVJreEtBSUJCWk8yOUNnamtNNk03ejAzMXVVLmpwZw.jpg',
  updated_at = now()
WHERE id = 'e212e65d-3f20-441e-ae88-d8581003532e';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono', 'field']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-professional-co-axial-master-chronometer-chronograph-42-mm-31030425001001-3ccf4a.png?w=1100',
  updated_at = now()
WHERE id = '9167a0ac-c80b-4f6e-9656-4ca594e27e17';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport', 'dress']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-professional-chronograph-42-mm-31130423001005-a20104.png?w=1100',
  updated_at = now()
WHERE id = '22dc3111-3e87-45e0-892a-69bc53d59298';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport', 'pilot']::text[],
  image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads//OmegaSpeedmasterProfessional145022-001.jpg',
  updated_at = now()
WHERE id = '46799878-e3ed-42ed-874e-4472533e3247';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport', 'dress', 'field']::text[],
  image_url = 'https://cdn.grayandsons.com/s/omega_speedmaster_42mm_145012_w529140_c258ef0a50-w1536.jpg.avif',
  updated_at = now()
WHERE id = '4c006762-b03d-42fe-a4a1-7dbea4cea8ac';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono', 'pilot']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-chronograph-42-mm-35705000-e5f892.png?w=1100',
  updated_at = now()
WHERE id = '9f40982f-10d4-4c56-a516-85bc619bb7be';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport', 'pilot']::text[],
  image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-vintage-speedmaster-_moon-watch_-35905000-c718fa.jpg?w=1100',
  updated_at = now()
WHERE id = 'bb356f1e-3b64-411a-b1b9-adce026af3e7';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport', 'pilot']::text[],
  image_url = 'https://www.cwwatchshop.com/cdn/shop/files/PhotoDec252023_11411PM.jpg?v=1716644736&width=960',
  updated_at = now()
WHERE id = 'cfbc3502-aac9-404c-bd20-35b5493119c2';

UPDATE watches_catalog SET
  movement_type = 'manual',
  case_size_mm = 37,
  style_tags = ARRAY['chrono', 'sport', 'vintage', 'racing']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2017/12/Screen-Shot-2021-06-21-at-2.11.44-PM.jpg',
  updated_at = now()
WHERE id = 'b04e9e65-4e4b-4aed-bff7-d9b63dd2b559';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['chrono', 'sport', 'dress', 'luxury']::text[],
  image_url = 'https://www.ssongwatches.com/cdn/shop/files/Rolex-Cosmograph-Daytona-Ref.-16520-Zenith-White_0018_Layer-109.png?v=1691482984',
  updated_at = now()
WHERE id = '9ea4fd5c-8519-4c13-8a47-b1e1a7e14c3d';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['chrono', 'sport', 'dress', 'luxury']::text[],
  image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2021/02/Rolex-Cosmograph-Daytona-116520.003.jpg',
  updated_at = now()
WHERE id = 'df751c49-2692-4e75-9aee-0ae51539d52a';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['chrono', 'sport', 'dress', 'racing']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126500ln-0001',
  updated_at = now()
WHERE id = '501bb888-4abd-419c-80a0-f754b113e9cb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['chrono', 'sport', 'racing', 'dress']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/02/Rolex_Daytona_5D3_4347-Edit-1.jpg',
  updated_at = now()
WHERE id = '0b0eb71b-8e1d-4029-a5f1-01267408ad2a';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 36,
  style_tags = ARRAY['dress', 'sport']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126234-0015',
  updated_at = now()
WHERE id = '0f655636-8c54-4ae7-a0ce-00c535782b56';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 36,
  style_tags = ARRAY['dress', 'sport']::text[],
  image_url = 'https://www.atlantaluxurywatches.com/images/medium_image/IMG_0010_4-Edit.jpg',
  updated_at = now()
WHERE id = '02a01e2b-acf3-4b1a-a1e4-76e7e16e58d6';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 36,
  style_tags = ARRAY['sport', 'field', 'dress']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m124270-0001',
  updated_at = now()
WHERE id = 'c7f54bfb-b2fa-4006-a8ee-e9a4162acf75';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 36,
  style_tags = ARRAY['sport', 'field', 'dress']::text[],
  image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2023/08/Rolex_Explorer_1016_Bulang_4.jpg',
  updated_at = now()
WHERE id = '87f24038-6073-4f1f-81ba-04dea8f2ff4d';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['sport', 'field', 'dress', 'tool']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/11/Rolex_Explorer_214270_20JM3550-Edit-3-1.jpg',
  updated_at = now()
WHERE id = 'f4d50aec-b6c3-4bbd-aee9-72cd1a5cd146';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'pilot', 'travel', 'vintage']::text[],
  image_url = 'https://cdn.watchcharts.com/removebg/955994b9-512b-435f-bf51-983bd46ebc4a.png?d=400x600',
  updated_at = now()
WHERE id = '400be415-74c7-477a-85e4-8b7d6ba870a2';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'pilot', 'travel']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126710blnr-0002',
  updated_at = now()
WHERE id = '2141ed12-8b6e-4691-9917-55076bd64dfd';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'pilot', 'travel', 'tool']::text[],
  image_url = 'https://millenarywatches.com/wp-content/uploads/2018/11/2770a1017904ad6e8766b4190f4c28d2d8ded56c.jpg',
  updated_at = now()
WHERE id = 'e26c0190-6fda-4785-af21-9cd13b6978eb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'pilot', 'travel']::text[],
  image_url = 'https://monochrome-watches.com/app/uploads/2018/03/Rolex-GMT-Master-II-Pepsi-126710-BLRO-Steel-Jubilee-Calibre-3285-Baselworld-2018-2.jpg',
  updated_at = now()
WHERE id = 'a6ff6a4d-613b-4b16-940a-d36a38a6f0e4';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['gmt', 'sport', 'pilot', 'tool', 'travel']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2016/04/Rolex-GMT-Master-II-116710LN.jpg',
  updated_at = now()
WHERE id = 'fecc36c6-0e70-48af-b5b4-d80855307c44';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 43,
  style_tags = ARRAY['dive', 'sport', 'tool']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126600-0002',
  updated_at = now()
WHERE id = 'c55d7391-6b33-49e1-95d2-afb9d0b6ffcb';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'tool']::text[],
  image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2024/01/Rolex-Sea-Dweller-16600-6.jpg',
  updated_at = now()
WHERE id = 'a6284c5d-11c1-487f-a651-493e1428687b';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'professional']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2026/02/Screen-Shot-2021-06-18-at-4.27.17-PM-edited.jpg',
  updated_at = now()
WHERE id = 'c6ccb57a-87ec-49f6-9ca1-a1c2625e19b3';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'field']::text[],
  image_url = 'https://alexanderscolumbus.com/cdn/shop/files/e300d4ed5c1280fb0c2bc10682564373_1080x.jpg?v=1767895972',
  updated_at = now()
WHERE id = '173ef234-1a5c-4781-bd58-cd6d40c27811';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'tool']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2025/11/Vintage-Rolex-Submariner-5513-edited.jpg',
  updated_at = now()
WHERE id = '3cd1a7eb-72fc-41fe-8d32-d321b8c1417a';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'dress']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2020/02/Screen-Shot-2021-02-04-at-1.11.44-PM.jpg',
  updated_at = now()
WHERE id = '9bc6ccbe-adec-4d3f-b86f-c6fafb67ef79';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126610ln-0001',
  updated_at = now()
WHERE id = '86c1937d-27c1-475d-b498-a77c023df697';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'dress']::text[],
  image_url = 'https://i0.wp.com/www.thetimebum.com/wp-content/uploads/2023/09/IMG_1336-1.jpeg?w=1800&ssl=1',
  updated_at = now()
WHERE id = '8775aebd-4112-41f0-9f77-d81eddc15627';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'date']::text[],
  image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2022/03/Screen-Shot-2022-05-10-at-11.44.50-PM.jpg',
  updated_at = now()
WHERE id = 'fc984342-be8b-459d-a810-287280ce9033';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://cdn.shopify.com/s/files/1/0612/0354/6292/files/rolex_submariner_114060.png?',
  updated_at = now()
WHERE id = '84d43d0f-b1b4-4243-95b6-4108d34a9036';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m124060-0001',
  updated_at = now()
WHERE id = 'aa4a114b-54ce-459c-8dfb-840a98a1e5af';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 40,
  style_tags = ARRAY['dive', 'sport', 'dress']::text[],
  image_url = 'https://www.luxurybazaar.com/cdn/uploads/2023/09/rolex_14060_304470_9286.jpg',
  updated_at = now()
WHERE id = '4d8d045d-1065-4767-a95c-3f1c8809a440';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42.5,
  style_tags = ARRAY['sport', 'dive']::text[],
  image_url = 'https://seikousa.com/cdn/shop/products/SRPD51_1_f6d6800e-4af6-46af-a2ac-5424adf62179.png?v=1744226993&width=990',
  updated_at = now()
WHERE id = '98d97c20-f942-4b92-a09b-a20cd7da55b5';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42.5,
  style_tags = ARRAY['sport', 'dive']::text[],
  image_url = 'https://cdn11.bigcommerce.com/s-e31c8/images/stencil/1280x1280/products/2134/18493/SBSA063__69680.1603054995.jpg?c=2',
  updated_at = now()
WHERE id = 'c2e7edac-717f-4027-8282-04b9aa753600';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 44,
  style_tags = ARRAY['dive', 'sport', 'vintage']::text[],
  image_url = 'https://journal.craftandtailored.com/wp-content/uploads/DSC05405-2_resized.jpeg.webp',
  updated_at = now()
WHERE id = '4c7c6942-981c-4579-b7f9-72c2e5ef2df8';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 37.5,
  style_tags = ARRAY['dive', 'sport', 'vintage', 'tool']::text[],
  image_url = 'https://www.ikigai-watches.com/wp-content/uploads/2018/06/Ik-18-007-2-768x1159.jpg',
  updated_at = now()
WHERE id = '7c6852ab-25e6-493e-8f92-0ed8263d3d94';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://thesamuraivintage.com/cdn/shop/products/vintage-watch-seiko-6309-7040-turtle-original-bezel-aged-to-a-dark-grey-finishing-124676.jpg?v=1697820308&width=1080',
  updated_at = now()
WHERE id = '6a608de1-c50a-4169-bdd9-d4a767e2a1a2';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 38,
  style_tags = ARRAY['field', 'sport', 'dress', 'outdoor']::text[],
  image_url = 'https://smalltoysforgrownmen.wordpress.com/wp-content/uploads/2017/06/sarb017-1.jpg',
  updated_at = now()
WHERE id = '5ecf013c-229a-4faa-b80f-4295e9f20772';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39.5,
  style_tags = ARRAY['field', 'sport', 'dive', 'dress']::text[],
  image_url = 'https://www.seikowatches.com/us-en/-/media/Images/Product--Image/America/Seiko/prospex/SPB121J1/SPB121J1.png?mh=1200&mw=1200',
  updated_at = now()
WHERE id = 'bef1ea69-7b14-4c97-849d-a126d203f290';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39.9,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.seikowatches.com/in-en/-/media/Images/GlobalEn/Seiko/Home/news/20170323-5500045078/04png.png',
  updated_at = now()
WHERE id = '6cff3235-d773-442e-952a-dc538001ff82';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.seikowatches.com/sg-en/-/media/Images/Product--Image/All/Seiko/2022/02/19/23/08/SLA033J1/SLA033J1.png?mh=1200&mw=1200',
  updated_at = now()
WHERE id = 'af1bcf54-d6bd-4313-96cd-fa84ec3064b1';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/640w/products/15307/57665/apicdqwdv__90322.1619741637.jpg?c=1',
  updated_at = now()
WHERE id = '2cd72016-d9d8-4316-80be-6bfedddca723';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.seikowatches.com/middleeast-en/-/media/Images/Product--Image/All/Seiko/2022/02/20/00/43/SPB101J1/SPB101J1.png?mh=1200&mw=1200',
  updated_at = now()
WHERE id = '83251af2-afe8-438e-8871-d4cd5bcb6ab4';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 44.3,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/640w/products/16455/72371/apioeyabd__92413.1619742636.jpg?c=1',
  updated_at = now()
WHERE id = 'a5cc76dc-934a-45a5-bac0-9e94818de62a';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 45,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://seikousa.com/cdn/shop/files/SRPE93_1_cc36718a-b6bb-4ed8-a66b-5346dd475784.png?v=1773081793&width=990',
  updated_at = now()
WHERE id = '9e74f1fa-bbb5-4944-b238-80682be2fdfd';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42.5,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://hodinkee.imgix.net/uploads/content_image/c32504cbf6a9cbd16cc3e53a45780e6e?ixlib=rails-1.1.0&fm=jpg&q=55&auto=format&usm=12&fit=crop&ch=Width%2CDPR%2CSave-Data&alt=&w=1400',
  updated_at = now()
WHERE id = '948ef89c-2f4e-47c7-9726-5126fe5647a4';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://cdnstatic.creationwatches.com/products/product-images/m/SKX009K1_MED.jpg',
  updated_at = now()
WHERE id = 'd6fd37cb-f74b-490f-9dd6-7f7813059e4b';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/1280w/products/14299/90249/squale-500-meter-dive-watch-1521-026-blr-1__25337.1636063891.jpg?c=1',
  updated_at = now()
WHERE id = '16cb2412-eb6d-41e1-8414-b89be87aa53c';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://www.steinhartwatches.de/media/catalog/product/cache/400e9658f7d23be7c232c45ce97a5cb0/1/_/1_frontal-1000x1000.png',
  updated_at = now()
WHERE id = 'a1e2fae2-ea0a-400d-89fc-13594bf5fe9a';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport', 'field', 'military']::text[],
  image_url = 'https://www.steinhartwatches.de/media/catalog/product/cache/400e9658f7d23be7c232c45ce97a5cb0/1/_/1_frontal_9_1.png',
  updated_at = now()
WHERE id = '3935ab19-2d72-40f6-961b-e363cc92f51a';

UPDATE watches_catalog SET
  movement_type = 'quartz',
  case_size_mm = 42,
  style_tags = ARRAY['chrono', 'sport']::text[],
  image_url = 'https://static.swatch.com/images/product/SO33G100/sa000/SO33G100_sa000_ec001m.png',
  updated_at = now()
WHERE id = '8f065dfc-8e96-4a4b-9ee2-b99013aa067a';

UPDATE watches_catalog SET
  movement_type = 'quartz',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono']::text[],
  image_url = 'https://www.swatch.com/dw/image/v2/BDNV_PRD/on/demandware.static/-/Library-Sites-swarp-global/default/dwecc23012/images/Swatch/collections/2022/moonswatch/New-LP/mercury_image1_1080x1290_m.jpg',
  updated_at = now()
WHERE id = '1e7aed78-9d7c-4bb0-bae1-ff97e6a3440b';

UPDATE watches_catalog SET
  movement_type = 'quartz',
  case_size_mm = 42,
  style_tags = ARRAY['sport', 'chrono']::text[],
  image_url = 'https://static.swatch.com/images/product/SO33M100/sa000/SO33M100_sa000_ec001m.png',
  updated_at = now()
WHERE id = '8cd60d5d-9d11-453a-8e22-ef8348f4dbea';

UPDATE watches_catalog SET
  movement_type = NULL,
  case_size_mm = NULL,
  style_tags = '{}'::text[],
  image_url = 'https://watchard.com/media/catalog/product/cache/3/image/1320x1584/s/m/3/9/cache/1920_smartwatch-meski-garett-v10-silver-steel-5904238485606-2.webp',
  updated_at = now()
WHERE id = '00000000-0000-4000-a000-000000000037';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['dive', 'sport', 'heritage']::text[],
  image_url = 'https://feedthewrist.com/wp-content/uploads/2023/07/image0-22.jpeg?w=2048',
  updated_at = now()
WHERE id = '9a930356-a8bb-4c3f-83b6-be20c25e6d6f';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dive', 'sport', 'vintage-inspired']::text[],
  image_url = 'https://cdn.watchcharts.com/removebg/99377d5c-a9bc-4c2b-b9f5-ea6e46c108fd.png?d=400x600',
  updated_at = now()
WHERE id = '9c58f983-23d4-4714-980b-adb9b29744a8';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['chrono', 'sport', 'dive']::text[],
  image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79360n-0011',
  updated_at = now()
WHERE id = 'c9892ccd-ae8e-4f04-af92-cb8e351d58f2';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 41,
  style_tags = ARRAY['gmt', 'dive', 'sport']::text[],
  image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79830rb-0001',
  updated_at = now()
WHERE id = '95fadf1a-89f4-419b-b7f7-8597f4862d6b';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['gmt', 'sport', 'field', 'dive', 'tool']::text[],
  image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79470-0001',
  updated_at = now()
WHERE id = 'a1fe0929-b51f-434b-a0ae-c1e24ade1b64';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 42,
  style_tags = ARRAY['dive', 'sport', 'tool']::text[],
  image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_3840/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m25600tn-0001-ab__black_rubber__4378688',
  updated_at = now()
WHERE id = 'f8c1596d-eb33-49b4-87cd-e5d9b037a7f0';

UPDATE watches_catalog SET
  movement_type = 'auto',
  case_size_mm = 39,
  style_tags = ARRAY['dive', 'sport']::text[],
  image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_3840/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m25407n-0001-ab__black_rubber__52970',
  updated_at = now()
WHERE id = '4d67cbfa-9f17-44c5-97d0-9abab206c9a0';

COMMIT;
