-- Phase 44 data migration: factual attributes matched by NATURAL KEY.
--
-- Generated from the verified local watches_catalog (100 enriched seed rows).
--
-- Why natural-key matching: the seed inserts watches_catalog rows WITHOUT an
-- id column, so id is gen_random_uuid()-assigned per seed run. Local and prod
-- were seeded separately, so the same 100 watches carry different ids in each
-- DB. The id-keyed migration (20260518113308_phase44_factual_data.sql) is a
-- no-op on prod. This migration matches on (brand, model, reference) — written
-- as literal text by the seed and therefore identical across both DBs.
--
-- Scope: the 100 seed watches only. Manually-added prod rows have distinct
-- brand/model/reference tuples and are left untouched.
-- Idempotent: re-running re-applies the same values.

BEGIN;

UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 36, style_tags = '{sport,dress,luxury-sport}'::text[], image_url = 'https://cdn.swisswatchexpo.com/productphotos/5/4/audemars-piguet-royal-oak-black-dial-steel-mens-watch-14790st-box-papers-51561_9a00be7fef_md.jpg', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak' AND reference = '14790ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{sport,dress,"luxury sport"}'::text[], image_url = 'https://www.acollectedman.com/cdn/shop/products/Audemars_Piguet_Royal_Oak_15300ST_Stainless_Steel_A_Collected_Man_London_WSS_A1315_09_2160x.jpg?v=1666367510', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak' AND reference = '15300ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{sport,dress,luxury-sport}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2017/07/AudmarsPiget-5D3_0397.jpg', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak' AND reference = '15400ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{sport,dress,luxury-sport,integrated-bracelet}'::text[], image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-598?size=716,0&fmt=avif-alpha&dpr=off', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak' AND reference = '15500ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{sport,dress,luxury-sport,integrated-bracelet}'::text[], image_url = 'https://cdn.swisswatchexpo.com/productphotos/12/28/audemars-piguet-royal-oak-jumbo-a-series-black-dial-steel-mens-watch-5402st-66829_ad7fd_md.jpg', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak' AND reference = '5402ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dress,sport,luxury}'::text[], image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-157?size=716,0&fmt=avif-alpha&dpr=off', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak Jumbo Extra-Thin' AND reference = '15202ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dress,sport,luxury}'::text[], image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-880?size=716,0&fmt=avif-alpha&dpr=off', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak Jumbo Extra-Thin' AND reference = '16202ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{sport,chrono,luxury-sport}'::text[], image_url = 'https://monochrome-watches.com/app/uploads/2022/12/Collector-Guide-First-Generation-Audemars-Piguet-Royal-Oak-Offshore-25721ST-23.jpg', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak Offshore' AND reference = '25721ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 43, style_tags = '{sport,chrono,luxury-sport}'::text[], image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-1068?size=716,0&fmt=avif-alpha&dpr=off', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak Offshore' AND reference = '26420SO';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{sport,chrono,luxury,dress}'::text[], image_url = 'https://dynamicmedia.audemarspiguet.com/is/image/audemarspiguet/watch-483?size=716,0&fmt=avif-alpha&dpr=off', updated_at = now() WHERE brand = 'Audemars Piguet' AND model = 'Royal Oak Offshore' AND reference = '26470ST';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 38, style_tags = '{dive,sport}'::text[], image_url = 'https://static.wixstatic.com/media/7ee37d_d8f27833bbbb4677b1c58e8d4980af73~mv2.webp/v1/fill/w_1526,h_1018,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/7ee37d_d8f27833bbbb4677b1c58e8d4980af73~mv2.webp', updated_at = now() WHERE brand = 'Christopher Ward' AND model = 'C60 Trident Pro 300' AND reference = 'C60-LDP38';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport}'::text[], image_url = 'https://www.christopherward.com/dw/image/v2/BDWD_PRD/on/demandware.static/-/Sites-cw-master-catalog/default/dw77871930/images/WATCHES/C60-40ADA31S0KK1-B0/C60-40ADA31S0KK1-B0_Picture_2.jpg?sw=2000&sh=2000', updated_at = now() WHERE brand = 'Christopher Ward' AND model = 'C60 Trident Pro 600' AND reference = 'C60-300';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 38, style_tags = '{dress}'::text[], image_url = 'https://substackcdn.com/image/fetch/$s_!KM2w!,w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F120d18b0-f1ee-43e4-9486-b6d5382c927e_500x423.jpeg', updated_at = now() WHERE brand = 'Grand Seiko' AND model = '44GS Recreation' AND reference = 'SBGW253';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39.5, style_tags = '{dress,gmt,sport}'::text[], image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGM221/SBGM221_dial.jpg', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Elegance' AND reference = 'SBGM221';
UPDATE watches_catalog SET movement_type = 'spring_drive', case_size_mm = 38.5, style_tags = '{dress,elegance}'::text[], image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGY007/SBGY007_dial.jpg?mh=1200&mw=1200&hash=E2B13B85D80435AEAAC1E8A90C57B188', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Elegance' AND reference = 'SBGY007';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40.2, style_tags = '{dress,sport,heritage}'::text[], image_url = 'https://www.grand-seiko.com/uk-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/22/00/SBGH205G/SBGH205G.png', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Hi-Beat 36000' AND reference = 'SBGH205';
UPDATE watches_catalog SET movement_type = 'spring_drive', case_size_mm = 40, style_tags = '{sport,dress}'::text[], image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/23/13/SLGA009G/SLGA009G.png', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Lake Suwa' AND reference = 'SLGA009';
UPDATE watches_catalog SET movement_type = 'spring_drive', case_size_mm = 41, style_tags = '{dress,sport}'::text[], image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/GlobalEn/GrandSeiko/Home/collections/Products/SBGA211/SBGA211_dial.jpg', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Snowflake' AND reference = 'SBGA011';
UPDATE watches_catalog SET movement_type = 'spring_drive', case_size_mm = 41, style_tags = '{dress,sport,heritage}'::text[], image_url = 'https://grandseikoboutique.us/cdn/shop/files/SBGA211-grand-seiko-watch-spring-drive-snowflake.png?v=1774888667', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Snowflake' AND reference = 'SBGA211';
UPDATE watches_catalog SET movement_type = 'spring_drive', case_size_mm = 44.2, style_tags = '{sport,dive}'::text[], image_url = 'https://grandseikoboutique.us/cdn/shop/products/Grand-Seiko-SBGA463-spring-drive-watch.png?v=1636490448&width=1200', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Sport' AND reference = 'SBGA463';
UPDATE watches_catalog SET movement_type = 'quartz', case_size_mm = 40, style_tags = '{gmt,sport,dress,travel}'::text[], image_url = 'https://images.ctfassets.net/517dkfc553yf/6jomZ0f9BPSGKreoAco2PT/94f2e19249c5486c4f18f0ad084d6739/SBGN013.jpg?w=1280&h=1398&fm=webp', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'Sport' AND reference = 'SBGN013';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dress,sport}'::text[], image_url = 'https://www.grand-seiko.com/us-en/-/media/Images/Product--Image/All/GrandSeiko/2022/02/19/23/14/SLGH005G/SLGH005G.png', updated_at = now() WHERE brand = 'Grand Seiko' AND model = 'White Birch' AND reference = 'SLGH005';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{field,military,dress,sport}'::text[], image_url = 'https://s.turbifycdn.com/aah/movadobaby/longines-heritage-military-1938-l2-788-4-53-0-67.jpg', updated_at = now() WHERE brand = 'Longines' AND model = 'Heritage Military 1938' AND reference = 'L2.788.1.53.0';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{field,military,dress,sport}'::text[], image_url = 'https://cdn.watchbase.com/watch/lg/origin:png/longines/heritage/l28324530-2f.webp', updated_at = now() WHERE brand = 'Longines' AND model = 'Heritage Military COSD' AND reference = 'L2.832.4.53.0';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-781-4-06-6-2799e4-hero.png?w=1920', updated_at = now() WHERE brand = 'Longines' AND model = 'HydroConquest 39mm' AND reference = 'L3.781.4.06.6';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-781-4-96-6-ddea24-hero.png?w=1920', updated_at = now() WHERE brand = 'Longines' AND model = 'HydroConquest 41mm' AND reference = 'L3.880.4.16.2';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport,heritage}'::text[], image_url = 'https://cdn.watchbase.com/watch/lg/origin:jpg/longines/heritage/l36744500-38.webp', updated_at = now() WHERE brand = 'Longines' AND model = 'Legend Diver' AND reference = 'L3.674.4.50.0';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport,heritage}'::text[], image_url = 'https://www.thetimepiececollection.com/media/catalog/product/cache/8060fbcc986bd45c6a23957550dd7450/l/3/l3.774.4.50.9_1_1__nempwe4jhc2q9hed.jpg', updated_at = now() WHERE brand = 'Longines' AND model = 'Legend Diver' AND reference = 'L3.774.4.50.9';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{pilot,sport,field,dress}'::text[], image_url = 'https://cdn.watchtime.com/watchtime_en-us/2020/06/Longines_Spirit_mattblack_front_1000_640.webp', updated_at = now() WHERE brand = 'Longines' AND model = 'Spirit 40mm' AND reference = 'L3.810.4.53.0';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{pilot,gmt,sport,field}'::text[], image_url = 'https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-spirit-zulu-time-l3-812-4-63-6-3ffc56-hero.png?w=1920', updated_at = now() WHERE brand = 'Longines' AND model = 'Spirit Zulu Time' AND reference = 'L3.812.4.63.6';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 34, style_tags = '{dress,vintage}'::text[], image_url = 'https://img.everywatch.com/media/2024/01/02/omega-constellation-168-00510470216.webp', updated_at = now() WHERE brand = 'Omega' AND model = 'Constellation' AND reference = '168.005';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dress,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-constellation-globemaster-co-axial-master-chronometer-39-mm-13033392102001-b7c8cb.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Constellation Globemaster' AND reference = '130.33.39.21.02.001';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-diver-300m-co-axial-master-chronometer-42-mm-21030422001001-23ffb2.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Seamaster Diver 300M' AND reference = '210.30.42.20.01.001';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-diver-300m-co-axial-chronometer-41-mm-21230412001003-bfcfd9.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Seamaster Diver 300M' AND reference = '212.30.41.20.01.003';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-300-m-chronometer-25318000-dc7fae.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Seamaster Diver 300M' AND reference = '2531.80';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 43.5, style_tags = '{dive,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-planet-ocean-600m-co-axial-master-chronometer-43-5-mm-21530442101001-8e6904.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Seamaster Planet Ocean' AND reference = '215.30.44.21.01.001';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45.5, style_tags = '{dive,sport}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-seamaster-planet-ocean-big-size-22005000-272076.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Seamaster Planet Ocean' AND reference = '2200.50';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 39.7, style_tags = '{chrono,sport,heritage,dress}'::text[], image_url = 'https://img.watchcrunch.com/rgpqmGDK7BQZf3sojdEIk1CbLNVcYZvPZcE0TxPgCAA/w:4096/h:320/rt:fit/g:sm/dpr:2/aW1nOi8vMjAyNS8wMi8xMi9yZmhEUHhmZFBlR05QTVJreEtBSUJCWk8yOUNnamtNNk03ejAzMXVVLmpwZw.jpg', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster' AND reference = 'CK2998';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{sport,chrono,field}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-professional-co-axial-master-chronometer-chronograph-42-mm-31030425001001-3ccf4a.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Moonwatch' AND reference = '310.30.42.50.01.001';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{chrono,sport,dress}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-professional-chronograph-42-mm-31130423001005-a20104.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Moonwatch' AND reference = '311.30.42.30.01.005';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{chrono,sport,pilot}'::text[], image_url = 'https://www.cwwatchshop.com/cdn/shop/files/PhotoDec252023_11411PM.jpg?v=1716644736&width=960', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Professional' AND reference = '105.012';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{chrono,sport,dress,field}'::text[], image_url = 'https://cdn.grayandsons.com/s/omega_speedmaster_42mm_145012_w529140_c258ef0a50-w1536.jpg.avif', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Professional' AND reference = '145.012';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{chrono,sport,pilot}'::text[], image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads//OmegaSpeedmasterProfessional145022-001.jpg', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Professional' AND reference = '145.022';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{sport,chrono,pilot}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-speedmaster-moonwatch-chronograph-42-mm-35705000-e5f892.png?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Professional' AND reference = '3570.50';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 42, style_tags = '{chrono,sport,pilot}'::text[], image_url = 'https://www.omegawatches.com/media/catalog/product/o/m/omega-vintage-speedmaster-_moon-watch_-35905000-c718fa.jpg?w=1100', updated_at = now() WHERE brand = 'Omega' AND model = 'Speedmaster Professional' AND reference = '3590.50';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{chrono,sport,racing,dress}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/02/Rolex_Daytona_5D3_4347-Edit-1.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Cosmograph Daytona' AND reference = '116500LN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{chrono,sport,dress,luxury}'::text[], image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2021/02/Rolex-Cosmograph-Daytona-116520.003.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Cosmograph Daytona' AND reference = '116520';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{chrono,sport,dress,racing}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126500ln-0001', updated_at = now() WHERE brand = 'Rolex' AND model = 'Cosmograph Daytona' AND reference = '126500LN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{chrono,sport,dress,luxury}'::text[], image_url = 'https://www.ssongwatches.com/cdn/shop/files/Rolex-Cosmograph-Daytona-Ref.-16520-Zenith-White_0018_Layer-109.png?v=1691482984', updated_at = now() WHERE brand = 'Rolex' AND model = 'Cosmograph Daytona' AND reference = '16520';
UPDATE watches_catalog SET movement_type = 'manual', case_size_mm = 37, style_tags = '{chrono,sport,vintage,racing}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2017/12/Screen-Shot-2021-06-21-at-2.11.44-PM.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Cosmograph Daytona' AND reference = '6263';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 36, style_tags = '{dress,sport}'::text[], image_url = 'https://www.atlantaluxurywatches.com/images/medium_image/IMG_0010_4-Edit.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Datejust 36' AND reference = '116234';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 36, style_tags = '{dress,sport}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126234-0015', updated_at = now() WHERE brand = 'Rolex' AND model = 'Datejust 36' AND reference = '126234';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 36, style_tags = '{sport,field,dress}'::text[], image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2023/08/Rolex_Explorer_1016_Bulang_4.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Explorer' AND reference = '1016';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 36, style_tags = '{sport,field,dress}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m124270-0001', updated_at = now() WHERE brand = 'Rolex' AND model = 'Explorer' AND reference = '124270';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{sport,field,dress,tool}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2021/11/Rolex_Explorer_214270_20JM3550-Edit-3-1.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Explorer' AND reference = '214270';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{gmt,sport,pilot,travel,vintage}'::text[], image_url = 'https://cdn.watchcharts.com/removebg/955994b9-512b-435f-bf51-983bd46ebc4a.png?d=400x600', updated_at = now() WHERE brand = 'Rolex' AND model = 'GMT-Master' AND reference = '1675';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{gmt,sport,pilot,tool,travel}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2016/04/Rolex-GMT-Master-II-116710LN.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'GMT-Master II' AND reference = '116710LN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{gmt,sport,pilot,travel}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126710blnr-0002', updated_at = now() WHERE brand = 'Rolex' AND model = 'GMT-Master II' AND reference = '126710BLNR';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{gmt,sport,pilot,travel}'::text[], image_url = 'https://monochrome-watches.com/app/uploads/2018/03/Rolex-GMT-Master-II-Pepsi-126710-BLRO-Steel-Jubilee-Calibre-3285-Baselworld-2018-2.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'GMT-Master II' AND reference = '126710BLRO';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{gmt,sport,pilot,travel,tool}'::text[], image_url = 'https://millenarywatches.com/wp-content/uploads/2018/11/2770a1017904ad6e8766b4190f4c28d2d8ded56c.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'GMT-Master II' AND reference = '16710';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,professional}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2026/02/Screen-Shot-2021-06-18-at-4.27.17-PM-edited.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Sea-Dweller' AND reference = '116600';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 43, style_tags = '{dive,sport,tool}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126600-0002', updated_at = now() WHERE brand = 'Rolex' AND model = 'Sea-Dweller' AND reference = '126600';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,tool}'::text[], image_url = 'https://www.fratellowatches.com/cdn-cgi/image/anim=false/wp-content/uploads/2024/01/Rolex-Sea-Dweller-16600-6.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Sea-Dweller' AND reference = '16600';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,field}'::text[], image_url = 'https://alexanderscolumbus.com/cdn/shop/files/e300d4ed5c1280fb0c2bc10682564373_1080x.jpg?v=1767895972', updated_at = now() WHERE brand = 'Rolex' AND model = 'Sea-Dweller' AND reference = '1665';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,tool}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2025/11/Vintage-Rolex-Submariner-5513-edited.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner' AND reference = '5513';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,dress}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2020/02/Screen-Shot-2021-02-04-at-1.11.44-PM.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner Date' AND reference = '116610LN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m126610ln-0001', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner Date' AND reference = '126610LN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,dress}'::text[], image_url = 'https://i0.wp.com/www.thetimebum.com/wp-content/uploads/2023/09/IMG_1336-1.jpeg?w=1800&ssl=1', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner Date' AND reference = '16610';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,date}'::text[], image_url = 'https://www.bobswatches.com/rolex-blog/wp-content/uploads/2022/03/Screen-Shot-2022-05-10-at-11.44.50-PM.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner Date' AND reference = '16800';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport}'::text[], image_url = 'https://cdn.shopify.com/s/files/1/0612/0354/6292/files/rolex_submariner_114060.png?', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner No-Date' AND reference = '114060';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport}'::text[], image_url = 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_1200/v1/a677b2c664f6/catalogue/2026/upright-c/m124060-0001', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner No-Date' AND reference = '124060';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 40, style_tags = '{dive,sport,dress}'::text[], image_url = 'https://www.luxurybazaar.com/cdn/uploads/2023/09/rolex_14060_304470_9286.jpg', updated_at = now() WHERE brand = 'Rolex' AND model = 'Submariner No-Date' AND reference = '14060M';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42.5, style_tags = '{sport,dive}'::text[], image_url = 'https://cdn11.bigcommerce.com/s-e31c8/images/stencil/1280x1280/products/2134/18493/SBSA063__69680.1603054995.jpg?c=2', updated_at = now() WHERE brand = 'Seiko' AND model = '5 Sports' AND reference = 'SBSA063';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42.5, style_tags = '{sport,dive}'::text[], image_url = 'https://seikousa.com/cdn/shop/products/SRPD51_1_f6d6800e-4af6-46af-a2ac-5424adf62179.png?v=1744226993&width=990', updated_at = now() WHERE brand = 'Seiko' AND model = '5 Sports' AND reference = 'SRPD51';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 44, style_tags = '{dive,sport,vintage}'::text[], image_url = 'https://journal.craftandtailored.com/wp-content/uploads/DSC05405-2_resized.jpeg.webp', updated_at = now() WHERE brand = 'Seiko' AND model = '6105-8110' AND reference = '6105-8110';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 37.5, style_tags = '{dive,sport,vintage,tool}'::text[], image_url = 'https://www.ikigai-watches.com/wp-content/uploads/2018/06/Ik-18-007-2-768x1159.jpg', updated_at = now() WHERE brand = 'Seiko' AND model = '62MAS' AND reference = '6217-8001';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45, style_tags = '{dive,sport}'::text[], image_url = 'https://thesamuraivintage.com/cdn/shop/products/vintage-watch-seiko-6309-7040-turtle-original-bezel-aged-to-a-dark-grey-finishing-124676.jpg?v=1697820308&width=1080', updated_at = now() WHERE brand = 'Seiko' AND model = '6309-7040' AND reference = '6309-7040';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 38, style_tags = '{field,sport,dress,outdoor}'::text[], image_url = 'https://smalltoysforgrownmen.wordpress.com/wp-content/uploads/2017/06/sarb017-1.jpg', updated_at = now() WHERE brand = 'Seiko' AND model = 'Alpinist' AND reference = 'SARB017';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39.5, style_tags = '{field,sport,dive,dress}'::text[], image_url = 'https://www.seikowatches.com/us-en/-/media/Images/Product--Image/America/Seiko/prospex/SPB121J1/SPB121J1.png?mh=1200&mw=1200', updated_at = now() WHERE brand = 'Seiko' AND model = 'Alpinist' AND reference = 'SPB121';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39.9, style_tags = '{dive,sport}'::text[], image_url = 'https://www.seikowatches.com/in-en/-/media/Images/GlobalEn/Seiko/Home/news/20170323-5500045078/04png.png', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex' AND reference = 'SLA017';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45, style_tags = '{dive,sport}'::text[], image_url = 'https://www.seikowatches.com/sg-en/-/media/Images/Product--Image/All/Seiko/2022/02/19/23/08/SLA033J1/SLA033J1.png?mh=1200&mw=1200', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex' AND reference = 'SLA033';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45, style_tags = '{dive,sport}'::text[], image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/640w/products/15307/57665/apicdqwdv__90322.1619741637.jpg?c=1', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex Sumo' AND reference = 'SBDC001';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45, style_tags = '{dive,sport}'::text[], image_url = 'https://www.seikowatches.com/middleeast-en/-/media/Images/Product--Image/All/Seiko/2022/02/20/00/43/SPB101J1/SPB101J1.png?mh=1200&mw=1200', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex Sumo' AND reference = 'SPB101';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 44.3, style_tags = '{dive,sport}'::text[], image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/640w/products/16455/72371/apioeyabd__92413.1619742636.jpg?c=1', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex Turtle' AND reference = 'SRP777';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 45, style_tags = '{dive,sport}'::text[], image_url = 'https://seikousa.com/cdn/shop/files/SRPE93_1_cc36718a-b6bb-4ed8-a66b-5346dd475784.png?v=1773081793&width=990', updated_at = now() WHERE brand = 'Seiko' AND model = 'Prospex Turtle' AND reference = 'SRPE93';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42.5, style_tags = '{dive,sport}'::text[], image_url = 'https://hodinkee.imgix.net/uploads/content_image/c32504cbf6a9cbd16cc3e53a45780e6e?ixlib=rails-1.1.0&fm=jpg&q=55&auto=format&usm=12&fit=crop&ch=Width%2CDPR%2CSave-Data&alt=&w=1400', updated_at = now() WHERE brand = 'Seiko' AND model = 'SKX007' AND reference = 'SKX007';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport}'::text[], image_url = 'https://cdnstatic.creationwatches.com/products/product-images/m/SKX009K1_MED.jpg', updated_at = now() WHERE brand = 'Seiko' AND model = 'SKX009' AND reference = 'SKX009';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport}'::text[], image_url = 'https://cdn11.bigcommerce.com/s-uzonwrhn18/images/stencil/1280w/products/14299/90249/squale-500-meter-dive-watch-1521-026-blr-1__25337.1636063891.jpg?c=1', updated_at = now() WHERE brand = 'Squale' AND model = '1521 Classic' AND reference = '1521-026';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dive,sport}'::text[], image_url = 'https://www.steinhartwatches.de/media/catalog/product/cache/400e9658f7d23be7c232c45ce97a5cb0/1/_/1_frontal-1000x1000.png', updated_at = now() WHERE brand = 'Steinhart' AND model = 'Ocean One 39' AND reference = 'Ocean-One-39';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport,field,military}'::text[], image_url = 'https://www.steinhartwatches.de/media/catalog/product/cache/400e9658f7d23be7c232c45ce97a5cb0/1/_/1_frontal_9_1.png', updated_at = now() WHERE brand = 'Steinhart' AND model = 'Ocean Vintage Military' AND reference = 'Ocean-OVM';
UPDATE watches_catalog SET movement_type = 'quartz', case_size_mm = 42, style_tags = '{chrono,sport}'::text[], image_url = 'https://static.swatch.com/images/product/SO33G100/sa000/SO33G100_sa000_ec001m.png', updated_at = now() WHERE brand = 'Swatch' AND model = 'MoonSwatch Mission to Earth' AND reference = 'SO33G100';
UPDATE watches_catalog SET movement_type = 'quartz', case_size_mm = 42, style_tags = '{sport,chrono}'::text[], image_url = 'https://www.swatch.com/dw/image/v2/BDNV_PRD/on/demandware.static/-/Library-Sites-swarp-global/default/dwecc23012/images/Swatch/collections/2022/moonswatch/New-LP/mercury_image1_1080x1290_m.jpg', updated_at = now() WHERE brand = 'Swatch' AND model = 'MoonSwatch Mission to Mars' AND reference = 'SO33A100';
UPDATE watches_catalog SET movement_type = 'quartz', case_size_mm = 42, style_tags = '{sport,chrono}'::text[], image_url = 'https://static.swatch.com/images/product/SO33M100/sa000/SO33M100_sa000_ec001m.png', updated_at = now() WHERE brand = 'Swatch' AND model = 'MoonSwatch Mission to the Moon' AND reference = 'SO33M100';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{dive,sport,heritage}'::text[], image_url = 'https://feedthewrist.com/wp-content/uploads/2023/07/image0-22.jpeg?w=2048', updated_at = now() WHERE brand = 'Tudor' AND model = 'Black Bay' AND reference = '79230N';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dive,sport,vintage-inspired}'::text[], image_url = 'https://cdn.watchcharts.com/removebg/99377d5c-a9bc-4c2b-b9f5-ea6e46c108fd.png?d=400x600', updated_at = now() WHERE brand = 'Tudor' AND model = 'Black Bay 58' AND reference = '79030N';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{chrono,sport,dive}'::text[], image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79360n-0011', updated_at = now() WHERE brand = 'Tudor' AND model = 'Black Bay Chrono' AND reference = '79360N';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 41, style_tags = '{gmt,dive,sport}'::text[], image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79830rb-0001', updated_at = now() WHERE brand = 'Tudor' AND model = 'Black Bay GMT' AND reference = '79830RB';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{gmt,sport,field,dive,tool}'::text[], image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_960/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m79470-0001', updated_at = now() WHERE brand = 'Tudor' AND model = 'Black Bay Pro' AND reference = '79470';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 42, style_tags = '{dive,sport,tool}'::text[], image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_3840/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m25600tn-0001-ab__black_rubber__4378688', updated_at = now() WHERE brand = 'Tudor' AND model = 'Pelagos' AND reference = '25600TN';
UPDATE watches_catalog SET movement_type = 'auto', case_size_mm = 39, style_tags = '{dive,sport}'::text[], image_url = 'https://media.tudorwatch.com/image/upload/q_auto/f_auto/t_tdr-cover-watch/c_limit,w_3840/v1/catalogue/0yi5ee8b69yh3/upright-cb-with-drop-shadow/tudor-m25407n-0001-ab__black_rubber__52970', updated_at = now() WHERE brand = 'Tudor' AND model = 'Pelagos 39' AND reference = '25407N';

COMMIT;
