'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import * as watchDAL from '@/data/watches'
import { logActivity } from '@/data/activities'
import { getCurrentUser, UnauthorizedError } from '@/lib/auth'
import type { ActionResult } from '@/lib/actionTypes'
import type { Watch } from '@/lib/types'

// Hand-written Zod schema — drizzle-orm/zod is not exported in this version.
// Mirrors all Watch fields except id (generated by DB).
const insertWatchSchema = z.object({
  brand: z.string().min(1, 'Brand is required'),
  model: z.string().min(1, 'Model is required'),
  reference: z.string().optional(),
  status: z.enum(['owned', 'wishlist', 'sold', 'grail']),
  pricePaid: z.number().optional(),
  targetPrice: z.number().optional(),
  marketPrice: z.number().optional(),
  movement: z.enum(['automatic', 'manual', 'quartz', 'spring-drive', 'other']),
  complications: z.array(z.string()).default([]),
  caseSizeMm: z.number().optional(),
  lugToLugMm: z.number().optional(),
  waterResistanceM: z.number().int().optional(),
  strapType: z.enum(['bracelet', 'leather', 'rubber', 'nato', 'other']).optional(),
  crystalType: z.enum(['sapphire', 'mineral', 'acrylic', 'hesalite', 'hardlex']).optional(),
  dialColor: z.string().optional(),
  styleTags: z.array(z.string()).default([]),
  designTraits: z.array(z.string()).default([]),
  roleTags: z.array(z.string()).default([]),
  acquisitionDate: z.string().optional(),
  productionYear: z.number().int().optional(),
  isFlaggedDeal: z.boolean().optional(),
  isChronometer: z.boolean().optional(),
  notes: z.string().optional(),
  imageUrl: z.string().optional(),
})

// Partial schema for updates — all fields optional.
const updateWatchSchema = insertWatchSchema.partial()

/**
 * Add a new watch to the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function addWatch(data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = insertWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  try {
    const watch = await watchDAL.createWatch(user.id, parsed.data)
    // Activity logging (D-05) — fire and forget, failure does not block mutation
    try {
      const activityType = watch.status === 'wishlist' || watch.status === 'grail'
        ? 'wishlist_added' as const
        : 'watch_added' as const
      await logActivity(user.id, activityType, watch.id, {
        brand: watch.brand,
        model: watch.model,
        imageUrl: watch.imageUrl ?? null,
      })
    } catch (err) {
      console.error('[addWatch] activity log failed (non-fatal):', err)
    }
    revalidatePath('/')
    return { success: true, data: watch }
  } catch (err) {
    console.error('[addWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to create watch' }
  }
}

/**
 * Update an existing watch.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates partial input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function editWatch(watchId: string, data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = updateWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  try {
    const watch = await watchDAL.updateWatch(user.id, watchId, parsed.data)
    revalidatePath('/')
    return { success: true, data: watch }
  } catch (err) {
    console.error('[editWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to update watch' }
  }
}

/**
 * Remove a watch from the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function removeWatch(watchId: string): Promise<ActionResult<void>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  try {
    await watchDAL.deleteWatch(user.id, watchId)
    revalidatePath('/')
    return { success: true, data: undefined }
  } catch (err) {
    console.error('[removeWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to delete watch' }
  }
}
