'use server'

import { revalidatePath, revalidateTag } from 'next/cache'
import { z } from 'zod'
import { eq, and } from 'drizzle-orm'
import { db } from '@/db'
import { divestments, watches } from '@/db/schema'
import * as watchDAL from '@/data/watches'
import * as catalogDAL from '@/data/catalog'
import { logActivity } from '@/data/activities'
import { getCurrentUser } from '@/lib/auth'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import { purgeWatchPhotos } from '@/app/actions/account'
import { logNotification } from '@/lib/notifications/logger'
import { findOverlapRecipients } from '@/data/notifications'
import { getProfileById } from '@/data/profiles'
import type { ActionResult } from '@/lib/actionTypes'
import type { Watch } from '@/lib/types'

// Hand-written Zod schema — drizzle-orm/zod is not exported in this version.
// Mirrors all Watch fields except id (generated by DB).
const insertWatchSchema = z.object({
  brand: z.string().min(1, 'Brand is required'),
  model: z.string().min(1, 'Model is required'),
  reference: z.string().optional(),
  status: z.enum(['owned', 'wishlist', 'sold', 'grail']),
  pricePaid: z.number().optional(),
  targetPrice: z.number().optional(),
  marketPrice: z.number().optional(),
  movement: z.enum(['auto', 'manual', 'quartz', 'spring_drive']).optional(),
  complications: z.array(z.string()).default([]),
  caseSizeMm: z.number().optional(),
  lugToLugMm: z.number().optional(),
  waterResistanceM: z.number().int().optional(),
  strapType: z.enum(['bracelet', 'leather', 'rubber', 'nato', 'other']).optional(),
  crystalType: z.enum(['sapphire', 'mineral', 'acrylic', 'hesalite', 'hardlex']).optional(),
  dialColor: z.string().optional(),
  styleTags: z.array(z.string()).default([]),
  designTraits: z.array(z.string()).default([]),
  roleTags: z.array(z.string()).default([]),
  acquisitionDate: z.string().optional(),
  productionYear: z.number().int().optional(),
  isFlaggedDeal: z.boolean().optional(),
  isChronometer: z.boolean().optional(),
  notes: z.string().optional(),
  notesPublic: z.boolean().optional(),
  imageUrl: z.string().optional(),
  // Phase 37 D-01..D-08: collector provenance fields (all optional)
  serial: z.string().optional(),
  yearOfAcquisition: z.number().int().min(1900).max(2100).optional(),
  condition: z.enum(['mint', 'near_mint', 'excellent', 'good', 'fair', 'poor']).optional(),
  boxPapers: z.enum(['none', 'box_only', 'papers_only', 'full_set']).optional(),
  serviceHistory: z.string().optional(),
  paidCurrency: z.enum(['USD', 'EUR', 'GBP', 'JPY', 'CHF', 'AUD', 'CAD', 'HKD', 'SGD', 'CNY']).optional(),
  purchaseDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format (use YYYY-MM-DD)').optional(),
  // Phase 27 (D-03/D-04) — accepted in the schema so the action can pass it
  // through after computing maxSort + 1 server-side. Client-supplied values
  // are silently overwritten by addWatch/editWatch when status enters the
  // wishlist+grail group; clients have no path to forge their own sort_order.
  sortOrder: z.number().int().optional(),
  // Phase 19.1 D-19: optional bucket path for the user-uploaded reference photo.
  // Format: "{userId}/{catalogId-or-pending}/{filename}.jpg" — server validates
  // userId segment matches the authenticated user (T-19.1-05-05).
  photoSourcePath: z.string()
    .regex(/^[0-9a-f-]{36}\/(pending|[0-9a-f-]{36})\/[0-9a-f-]+\.jpg$/i, 'Invalid photo path')
    .max(256)
    .optional(),
})

// Partial schema for updates — all fields optional.
const updateWatchSchema = insertWatchSchema.partial()

/**
 * Add a new watch to the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function addWatch(data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = insertWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  // T-19.1-05-05: photoSourcePath ownership check.
  // The first path segment MUST equal the authenticated user's id.
  if (parsed.data.photoSourcePath) {
    const firstSegment = parsed.data.photoSourcePath.split('/')[0]
    if (firstSegment !== user.id) {
      return { success: false, error: 'Photo path does not match authenticated user' }
    }
  }

  try {
    // Phase 27 D-03 — new wishlist/grail watch lands at end of the user's
    // wishlist+grail list. Universal column on every row, but we only assign
    // an explicit value when the new watch enters the wishlist+grail set.
    // For owned/sold the DB-side default 0 is fine (Collection-tab reorder
    // is deferred per CONTEXT).
    //
    // WR-01 fix — strip client-supplied sortOrder unconditionally before
    // passing to the DAL. The schema accepts the field (back-compat) but
    // the server is the SOLE source of truth for sortOrder values.
    // Without this, a malicious client could set sortOrder: -999999 to
    // force their watch to the top of their own list, bypassing the
    // bulkReorderWishlist 500-id cap.
    const { sortOrder: _ignoredSortOrder, ...cleanData } = parsed.data
    void _ignoredSortOrder
    // Payload type widens cleanData to allow re-adding sortOrder server-side.
    let createPayload: typeof parsed.data = cleanData
    if (cleanData.status === 'wishlist' || cleanData.status === 'grail') {
      const maxSort = await watchDAL.getMaxWishlistSortOrder(user.id)
      createPayload = { ...cleanData, sortOrder: maxSort + 1 }
    }

    // Phase 38 D-06 step 2a: catalog upsert BEFORE createWatch (fail-loud).
    // Pre-Phase-38 this was fire-and-forget after createWatch; post-Phase-38
    // catalog_id is NOT NULL so a failed upsert must block the insert.
    let catalogIdResult: string | null
    try {
      catalogIdResult = await catalogDAL.upsertCatalogFromUserInput({
        brand: parsed.data.brand,
        model: parsed.data.model,
        reference: parsed.data.reference ?? null,
      })
    } catch (err) {
      console.error('[addWatch] catalog upsert failed (fatal post-Phase-38 — catalog_id is NOT NULL):', err)
      throw err // fail-loud: cannot insert watches row without catalogId
    }
    if (!catalogIdResult) {
      throw new Error('[addWatch] catalog upsert returned null — cannot insert watches row without catalogId')
    }
    const catalogId: string = catalogIdResult

    const watch = await watchDAL.createWatch(user.id, catalogId, createPayload)
    // linkWatchToCatalog call REMOVED — createWatch now sets catalogId atomically (Phase 38 D-06).

    // Phase 19.1 D-08, D-09: catalog taste enrichment (fire-and-forget).
    // - If photoSourcePath set: write photo through to catalog image_url first (D-21).
    // - Enricher runs text-mode (no photo) or vision-mode (with photo bucket path).
    // - All operations are fire-and-forget; failures non-fatal per D-09.
    // - Await semantics: Option A (synchronous await inside addWatch) per plan recommendation.
    //   Adds ~1-3s latency but guarantees the enrichment write completes. Acceptable at v4.0 scale.
    if (catalogId) {
      const photoPath = parsed.data.photoSourcePath ?? null

      // D-21 photo write-through (only when photo present).
      if (photoPath) {
        try {
          const { getCatalogSourcePhotoSignedUrl } = await import('@/lib/storage/catalogSourcePhotos')
          // 7-day TTL signed URL for catalog image_url.
          // Production posture should switch to public-bucket reads or per-request signing.
          // Documented as deferred polish (Phase 19.1 SUMMARY).
          const longSignedUrl = await getCatalogSourcePhotoSignedUrl(photoPath, 60 * 60 * 24 * 7)
          if (longSignedUrl) {
            await catalogDAL.applyUserUploadedPhoto(catalogId, {
              imageUrl: longSignedUrl,
              imageSourceUrl: photoPath,
            })
          }
        } catch (err) {
          console.error('[addWatch] photo write-through failed (non-fatal):', err)
        }
      }

      // D-08 enrichment dispatch — awaited (Option A) for correctness at v4.0 scale.
      try {
        const { enrichTasteAttributes } = await import('@/lib/taste/enricher')
        const taste = await enrichTasteAttributes({
          catalogId,
          source: 'manual',
          spec: {
            brand: parsed.data.brand,
            model: parsed.data.model,
            reference: parsed.data.reference ?? null,
            movement: parsed.data.movement ?? null,
            caseSizeMm: parsed.data.caseSizeMm ?? null,
            lugToLugMm: parsed.data.lugToLugMm ?? null,
            waterResistanceM: parsed.data.waterResistanceM ?? null,
            crystalType: parsed.data.crystalType ?? null,
            dialColor: parsed.data.dialColor ?? null,
            isChronometer: parsed.data.isChronometer ?? null,
            productionYear: parsed.data.productionYear ?? null,
            complications: parsed.data.complications ?? [],
          },
          photoSourcePath: photoPath,
        })
        if (taste) {
          await catalogDAL.updateCatalogTaste(catalogId, taste)
        }
      } catch (err) {
        console.error('[addWatch] taste enrichment failed (non-fatal):', err)
      }
    }

    // Activity logging (D-05) — fire and forget, failure does not block mutation
    try {
      // Split branches so TypeScript can narrow the discriminated-union overload
      // (a union variable for `type` does not satisfy any single overload signature).
      if (watch.status === 'wishlist' || watch.status === 'grail') {
        await logActivity(user.id, 'wishlist_added', watch.id, {
          brand: watch.brand,
          model: watch.model,
          imageUrl: watch.imageUrl ?? null,
        })
      } else {
        await logActivity(user.id, 'watch_added', watch.id, {
          brand: watch.brand,
          model: watch.model,
          imageUrl: watch.imageUrl ?? null,
        })
      }
    } catch (err) {
      console.error('[addWatch] activity log failed (non-fatal):', err)
    }

    // NOTIF-03 — watch-overlap notifications. Only fire for owned status (D-23
    // self-exclusion is inside findOverlapRecipients; non-owned wishlist/grail
    // adds do NOT create overlap notifications per RESEARCH Open Q #1 — literal
    // reading of "another collector already owns").
    if (watch.status === 'owned') {
      try {
        const recipients = await findOverlapRecipients({
          brand: watch.brand,
          model: watch.model,
          actorUserId: user.id,
        })
        if (recipients.length > 0) {
          // Pre-resolve actor profile once — denormalize into payload per D-20.
          const actorProfile = await getProfileById(user.id)
          const brandNormalized = watch.brand.trim().toLowerCase()
          const modelNormalized = watch.model.trim().toLowerCase()
          for (const recipient of recipients) {
            // Awaited per-recipient (was fire-and-forget). Next 16 workAsyncStorage
            // is torn down when the action returns, so we need the insert to
            // complete before revalidateTag — otherwise the bell refetch could
            // race the insert and re-cache "no unread" for up to 30s. Logger's
            // internal try/catch (Plan 02 D-27) guarantees no throw, so the D-28
            // "logger failure can't roll back the watch add" contract is preserved.
            // Opt-out check (D-18) + dedup UNIQUE constraint handle edge cases
            // inside the logger itself.
            await logNotification({
              type: 'watch_overlap',
              recipientUserId: recipient.userId,
              actorUserId: user.id,
              payload: {
                actor_username: actorProfile?.username ?? '',
                actor_display_name: actorProfile?.displayName ?? null,
                watch_id: watch.id,
                watch_brand: watch.brand,
                watch_model: watch.model,
                watch_brand_normalized: brandNormalized,
                watch_model_normalized: modelNormalized,
              },
            })
            // RESEARCH Pitfall 6 — invalidate the RECIPIENT's NotificationBell
            // cache so their unread dot lights up on next render. Bug fix (debug
            // session notifications-revalidate-tag-in-render): previously no
            // invalidation happened on the watch_overlap write path.
            revalidateTag(`viewer:${recipient.userId}`, 'max')
          }
        }
      } catch (err) {
        // Overlap lookup failures are non-fatal — never block the watch add.
        console.error('[addWatch] overlap lookup failed (non-fatal):', err)
      }
    }

    revalidatePath('/')
    revalidatePath('/u/[username]', 'layout')

    // Phase 39c D-39c-04 — invalidate the owner's cached profile shell so the
    // next /u/{owner} render reflects the new watch count, taste tags, and
    // wear-event aggregates derived inside <ProfileShellResolver/>.
    // Cross-user fan-out via revalidateTag(tag, 'max').
    const ownerProfile = await getProfileById(user.id)
    if (ownerProfile?.username) {
      revalidateTag(`profile:${ownerProfile.username}`, 'max')
    }

    // Phase 18 DISC-05 / DISC-06 — fan out 'explore' tag so the global
    // Trending + Gaining Traction rails (and the per-viewer Popular Collectors
    // rail, which also tags 'explore') recompute on next render. Cross-user
    // semantics via revalidateTag(tag, 'max') — Pitfall 4. Granularity is
    // intentionally broad (just 'explore') rather than per-rail, per RESEARCH
    // §Pattern 6 recommendation. Fires once regardless of status because
    // both Trending (owners + 0.5*wishlist) and Gaining Traction read the
    // denormalized counts from the catalog.
    revalidateTag('explore', 'max')

    return { success: true, data: watch }
  } catch (err) {
    console.error('[addWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to create watch' }
  }
}

/**
 * Update an existing watch.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates partial input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function editWatch(watchId: string, data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = updateWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  try {
    // Phase 27 D-04 — status transition resets sort_order in the destination
    // group. Wishlist+grail share one group; owned+sold are a separate group
    // (Collection-tab reorder is deferred per CONTEXT, so we do not bump on
    // owned/sold transitions today). Only bump when:
    //   - parsed.data.status is 'wishlist' or 'grail', AND
    //   - the watch's CURRENT status is NOT wishlist/grail (transition INTO).
    // Within-group changes (wishlist ↔ grail) keep their slot — wishlist+grail
    // share the same sort_order space (D-05) so a within-group swap doesn't
    // change the bucket.
    //
    // WR-01 fix — strip client-supplied sortOrder unconditionally. The schema
    // accepts the field (back-compat) but the server is the SOLE source of
    // truth. Without this strip, a malicious client could clobber a
    // server-assigned slot during a within-group edit (the prior code only
    // bumped on TRANSITIONS into the group, leaving same-group edits to pass
    // sortOrder through untouched).
    const { sortOrder: _ignoredSortOrder, ...cleanData } = parsed.data
    void _ignoredSortOrder
    // Payload type widens cleanData to allow re-adding sortOrder server-side.
    let updatePayload: typeof parsed.data = cleanData

    // Phase 37 — single hoisted fetch. priorRow is used by:
    //   (1) the null/ownership early-return (WARNING #4 — prevents UPDATE on a
    //       row that was deleted between fetch and write, mirrors the pattern
    //       used inside recordDivestment in src/app/actions/divestments.ts);
    //   (2) the existing wishlist/grail sort-order logic (was a separate
    //       in-branch fetch — folded in so we only round-trip once);
    //   (3) the owned→sold transition detection (CRITICAL OVERRIDE #2).
    const priorRow = await watchDAL.getWatchById(user.id, watchId)
    if (!priorRow) {
      return { success: false, error: 'Watch not found' }
    }

    // Phase 27 D-04 — wishlist/grail sort-order assignment on transition INTO
    // the group. Reuses priorRow (single fetch above — no duplicate round-trip).
    if (cleanData.status === 'wishlist' || cleanData.status === 'grail') {
      const wasInWishlistGroup =
        priorRow.status === 'wishlist' || priorRow.status === 'grail'
      if (!wasInWishlistGroup) {
        const maxSort = await watchDAL.getMaxWishlistSortOrder(user.id)
        updatePayload = { ...cleanData, sortOrder: maxSort + 1 }
      }
    }

    // Phase 37 D-11 + CRITICAL OVERRIDE #2 — owned→sold transition detection.
    // If the user is flipping status to 'sold' AND the watch was not already
    // 'sold', the dual-write (INSERT divestments + UPDATE watches.status='sold')
    // MUST be atomic. Wrap both writes in db.transaction() — the FIRST
    // transaction usage in this codebase per RESEARCH §4 Open Q #2.
    //
    // For all other status transitions (and non-status edits), the existing
    // single-write updateWatch path is preserved. priorRow is non-null here
    // by virtue of the early-return above.
    let updatedWatch: Watch
    const isTransitioningToSold =
      updatePayload.status === 'sold' && priorRow.status !== 'sold'

    if (isTransitioningToSold) {
      // D-11 step 2: post-CAT-14 invariant — watches.catalog_id IS NOT NULL.
      // Defensive guard because Drizzle .notNull() tightening is Phase 38 (L-09).
      if (!priorRow.catalogId) {
        return { success: false, error: 'Watch has no catalog link — cannot transition to sold' }
      }

      // D-11 step 3 + 4: atomic dual-write.
      // Insert divestment row + apply the full update payload (which includes
      // status='sold' and any other concurrent edits the user made on the form).
      // divestedAt + createdAt + updatedAt default at DB level.
      // Option (b): inline the watches UPDATE directly inside the transaction
      // to avoid modifying updateWatch's signature (DAL accepts Partial<Watch>
      // but db.transaction's tx type doesn't thread cleanly through the DAL
      // without a signature change — inline is cleaner per plan Task 2 guidance).
      updatedWatch = await db.transaction(async (tx) => {
        await tx.insert(divestments).values({
          catalogId: priorRow.catalogId!,
          userId: user.id,
          // Phase 37 D-12: status-chip click writes empty-metadata row.
          // The future v5.x sell-dialog backfills salePrice / saleCurrency /
          // replacedByCatalogId / notes via a separate recordDivestment call.
        })
        // Apply the full updatePayload INSIDE the transaction so any
        // concurrent provenance edits the user made (e.g. condition, serial)
        // land atomically with the status flip.
        const rowData = Object.fromEntries(
          Object.entries(updatePayload).filter(([, v]) => v !== undefined)
        )
        const [updated] = await tx
          .update(watches)
          .set({ ...rowData, updatedAt: new Date() })
          .where(and(eq(watches.userId, user.id), eq(watches.id, watchId)))
          .returning()
        if (!updated) {
          throw new Error(`Watch not found or access denied: watchId=${watchId}, userId=${user.id}`)
        }
        return updated as unknown as Watch
      })
    } else {
      // Non-transition path — preserves existing behavior verbatim.
      // priorRow is non-null here (early-return above guarantees it), so the
      // updateWatch call cannot race a concurrent delete that started before
      // priorRow was fetched.
      updatedWatch = await watchDAL.updateWatch(user.id, watchId, updatePayload)
    }

    const watch = updatedWatch
    revalidatePath('/')
    revalidatePath('/u/[username]', 'layout')

    // Phase 39c D-39c-04 — invalidate the owner's cached profile shell so the
    // next /u/{owner} render reflects the new watch count, taste tags, and
    // wear-event aggregates derived inside <ProfileShellResolver/>.
    // Cross-user fan-out via revalidateTag(tag, 'max').
    const ownerProfile = await getProfileById(user.id)
    if (ownerProfile?.username) {
      revalidateTag(`profile:${ownerProfile.username}`, 'max')
    }

    // Phase 18 DISC-05 / DISC-06 — same fan-out as addWatch. editWatch can
    // change status (owned ↔ wishlist ↔ sold ↔ grail), and each transition
    // shifts the catalog's denormalized counts (owners_count, wishlist_count)
    // on the next pg_cron refresh. Even non-status edits (brand/model fixes)
    // can affect Trending if they re-link the watch to a different catalog
    // row via the upsert path. Fan-out is the safe default.
    revalidateTag('explore', 'max')

    return { success: true, data: watch }
  } catch (err) {
    console.error('[editWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to update watch' }
  }
}

/**
 * Remove a watch from the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function removeWatch(watchId: string): Promise<ActionResult<void>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  try {
    // Phase 60 T-60-ORPHAN: purge watch-photos storage objects BEFORE deleteWatch.
    // DB-first: purgeWatchPhotos queries watch_photos storagePaths then removes from storage.
    // CASCADE handles the watch_photos DB rows when deleteWatch fires.
    const supabase = await createSupabaseServerClient()
    await purgeWatchPhotos(supabase, watchId)

    await watchDAL.deleteWatch(user.id, watchId)
    revalidatePath('/')

    // Phase 39c D-39c-04 — invalidate the owner's cached profile shell so the
    // next /u/{owner} render reflects the new watch count, taste tags, and
    // wear-event aggregates derived inside <ProfileShellResolver/>.
    // Cross-user fan-out via revalidateTag(tag, 'max').
    const ownerProfile = await getProfileById(user.id)
    if (ownerProfile?.username) {
      revalidateTag(`profile:${ownerProfile.username}`, 'max')
    }

    // Phase 18 DISC-05 / DISC-06 — same fan-out as addWatch/editWatch.
    // DELETE on watches table → owners_count or wishlist_count decrements
    // on next pg_cron refresh, so the rails must recompute to reflect the
    // removal. Fan-out via revalidateTag(tag, 'max') — Pitfall 4.
    revalidateTag('explore', 'max')

    return { success: true, data: undefined }
  } catch (err) {
    console.error('[removeWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to delete watch' }
  }
}
