'use server'

import { revalidatePath, revalidateTag } from 'next/cache'
import { z } from 'zod'
import * as watchDAL from '@/data/watches'
import * as catalogDAL from '@/data/catalog'
import { logActivity } from '@/data/activities'
import { getCurrentUser } from '@/lib/auth'
import { logNotification } from '@/lib/notifications/logger'
import { findOverlapRecipients } from '@/data/notifications'
import { getProfileById } from '@/data/profiles'
import type { ActionResult } from '@/lib/actionTypes'
import type { Watch } from '@/lib/types'

// Hand-written Zod schema — drizzle-orm/zod is not exported in this version.
// Mirrors all Watch fields except id (generated by DB).
const insertWatchSchema = z.object({
  brand: z.string().min(1, 'Brand is required'),
  model: z.string().min(1, 'Model is required'),
  reference: z.string().optional(),
  status: z.enum(['owned', 'wishlist', 'sold', 'grail']),
  pricePaid: z.number().optional(),
  targetPrice: z.number().optional(),
  marketPrice: z.number().optional(),
  movement: z.enum(['automatic', 'manual', 'quartz', 'spring-drive', 'other']),
  complications: z.array(z.string()).default([]),
  caseSizeMm: z.number().optional(),
  lugToLugMm: z.number().optional(),
  waterResistanceM: z.number().int().optional(),
  strapType: z.enum(['bracelet', 'leather', 'rubber', 'nato', 'other']).optional(),
  crystalType: z.enum(['sapphire', 'mineral', 'acrylic', 'hesalite', 'hardlex']).optional(),
  dialColor: z.string().optional(),
  styleTags: z.array(z.string()).default([]),
  designTraits: z.array(z.string()).default([]),
  roleTags: z.array(z.string()).default([]),
  acquisitionDate: z.string().optional(),
  productionYear: z.number().int().optional(),
  isFlaggedDeal: z.boolean().optional(),
  isChronometer: z.boolean().optional(),
  notes: z.string().optional(),
  imageUrl: z.string().optional(),
  // Phase 27 (D-03/D-04) — accepted in the schema so the action can pass it
  // through after computing maxSort + 1 server-side. Client-supplied values
  // are silently overwritten by addWatch/editWatch when status enters the
  // wishlist+grail group; clients have no path to forge their own sort_order.
  sortOrder: z.number().int().optional(),
  // Phase 19.1 D-19: optional bucket path for the user-uploaded reference photo.
  // Format: "{userId}/{catalogId-or-pending}/{filename}.jpg" — server validates
  // userId segment matches the authenticated user (T-19.1-05-05).
  photoSourcePath: z.string()
    .regex(/^[0-9a-f-]{36}\/(pending|[0-9a-f-]{36})\/[0-9a-f-]+\.jpg$/i, 'Invalid photo path')
    .max(256)
    .optional(),
})

// Partial schema for updates — all fields optional.
const updateWatchSchema = insertWatchSchema.partial()

/**
 * Add a new watch to the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function addWatch(data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = insertWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  // T-19.1-05-05: photoSourcePath ownership check.
  // The first path segment MUST equal the authenticated user's id.
  if (parsed.data.photoSourcePath) {
    const firstSegment = parsed.data.photoSourcePath.split('/')[0]
    if (firstSegment !== user.id) {
      return { success: false, error: 'Photo path does not match authenticated user' }
    }
  }

  try {
    // Phase 27 D-03 — new wishlist/grail watch lands at end of the user's
    // wishlist+grail list. Universal column on every row, but we only assign
    // an explicit value when the new watch enters the wishlist+grail set.
    // For owned/sold the DB-side default 0 is fine (Collection-tab reorder
    // is deferred per CONTEXT). Server-side overwrites any client sortOrder.
    let createPayload: typeof parsed.data = parsed.data
    if (parsed.data.status === 'wishlist' || parsed.data.status === 'grail') {
      const maxSort = await watchDAL.getMaxWishlistSortOrder(user.id)
      createPayload = { ...parsed.data, sortOrder: maxSort + 1 }
    }

    const watch = await watchDAL.createWatch(user.id, createPayload)

    // CAT-08 — catalog wiring (fire-and-forget; mirrors logActivity pattern).
    // Split try/catch so the failure mode is identifiable in logs:
    //   - "catalog upsert failed" leaves the watch unlinked until URL extraction or
    //     the next nightly backfill creates the catalog row.
    //   - "catalog link failed" leaves a catalog row that exists but is not linked
    //     to this watch; the next backfill auto-cures it (idempotent — see
    //     phase17-backfill-idempotency.test.ts).
    let catalogId: string | null = null
    try {
      catalogId = await catalogDAL.upsertCatalogFromUserInput({
        brand: parsed.data.brand,
        model: parsed.data.model,
        reference: parsed.data.reference ?? null,
      })
    } catch (err) {
      console.error('[addWatch] catalog upsert failed (non-fatal):', err)
    }
    if (catalogId) {
      try {
        await watchDAL.linkWatchToCatalog(user.id, watch.id, catalogId)
      } catch (err) {
        console.error('[addWatch] catalog link failed (non-fatal):', err)
      }
    }

    // Phase 19.1 D-08, D-09: catalog taste enrichment (fire-and-forget).
    // - If photoSourcePath set: write photo through to catalog image_url first (D-21).
    // - Enricher runs text-mode (no photo) or vision-mode (with photo bucket path).
    // - All operations are fire-and-forget; failures non-fatal per D-09.
    // - Await semantics: Option A (synchronous await inside addWatch) per plan recommendation.
    //   Adds ~1-3s latency but guarantees the enrichment write completes. Acceptable at v4.0 scale.
    if (catalogId) {
      const photoPath = parsed.data.photoSourcePath ?? null

      // D-21 photo write-through (only when photo present).
      if (photoPath) {
        try {
          const { getCatalogSourcePhotoSignedUrl } = await import('@/lib/storage/catalogSourcePhotos')
          // 7-day TTL signed URL for catalog image_url.
          // Production posture should switch to public-bucket reads or per-request signing.
          // Documented as deferred polish (Phase 19.1 SUMMARY).
          const longSignedUrl = await getCatalogSourcePhotoSignedUrl(photoPath, 60 * 60 * 24 * 7)
          if (longSignedUrl) {
            await catalogDAL.applyUserUploadedPhoto(catalogId, {
              imageUrl: longSignedUrl,
              imageSourceUrl: photoPath,
            })
          }
        } catch (err) {
          console.error('[addWatch] photo write-through failed (non-fatal):', err)
        }
      }

      // D-08 enrichment dispatch — awaited (Option A) for correctness at v4.0 scale.
      try {
        const { enrichTasteAttributes } = await import('@/lib/taste/enricher')
        const taste = await enrichTasteAttributes({
          catalogId,
          source: 'manual',
          spec: {
            brand: parsed.data.brand,
            model: parsed.data.model,
            reference: parsed.data.reference ?? null,
            movement: parsed.data.movement,
            caseSizeMm: parsed.data.caseSizeMm ?? null,
            lugToLugMm: parsed.data.lugToLugMm ?? null,
            waterResistanceM: parsed.data.waterResistanceM ?? null,
            crystalType: parsed.data.crystalType ?? null,
            dialColor: parsed.data.dialColor ?? null,
            isChronometer: parsed.data.isChronometer ?? null,
            productionYear: parsed.data.productionYear ?? null,
            complications: parsed.data.complications ?? [],
          },
          photoSourcePath: photoPath,
        })
        if (taste) {
          await catalogDAL.updateCatalogTaste(catalogId, taste)
        }
      } catch (err) {
        console.error('[addWatch] taste enrichment failed (non-fatal):', err)
      }
    }

    // Activity logging (D-05) — fire and forget, failure does not block mutation
    try {
      // Split branches so TypeScript can narrow the discriminated-union overload
      // (a union variable for `type` does not satisfy any single overload signature).
      if (watch.status === 'wishlist' || watch.status === 'grail') {
        await logActivity(user.id, 'wishlist_added', watch.id, {
          brand: watch.brand,
          model: watch.model,
          imageUrl: watch.imageUrl ?? null,
        })
      } else {
        await logActivity(user.id, 'watch_added', watch.id, {
          brand: watch.brand,
          model: watch.model,
          imageUrl: watch.imageUrl ?? null,
        })
      }
    } catch (err) {
      console.error('[addWatch] activity log failed (non-fatal):', err)
    }

    // NOTIF-03 — watch-overlap notifications. Only fire for owned status (D-23
    // self-exclusion is inside findOverlapRecipients; non-owned wishlist/grail
    // adds do NOT create overlap notifications per RESEARCH Open Q #1 — literal
    // reading of "another collector already owns").
    if (watch.status === 'owned') {
      try {
        const recipients = await findOverlapRecipients({
          brand: watch.brand,
          model: watch.model,
          actorUserId: user.id,
        })
        if (recipients.length > 0) {
          // Pre-resolve actor profile once — denormalize into payload per D-20.
          const actorProfile = await getProfileById(user.id)
          const brandNormalized = watch.brand.trim().toLowerCase()
          const modelNormalized = watch.model.trim().toLowerCase()
          for (const recipient of recipients) {
            // Awaited per-recipient (was fire-and-forget). Next 16 workAsyncStorage
            // is torn down when the action returns, so we need the insert to
            // complete before revalidateTag — otherwise the bell refetch could
            // race the insert and re-cache "no unread" for up to 30s. Logger's
            // internal try/catch (Plan 02 D-27) guarantees no throw, so the D-28
            // "logger failure can't roll back the watch add" contract is preserved.
            // Opt-out check (D-18) + dedup UNIQUE constraint handle edge cases
            // inside the logger itself.
            await logNotification({
              type: 'watch_overlap',
              recipientUserId: recipient.userId,
              actorUserId: user.id,
              payload: {
                actor_username: actorProfile?.username ?? '',
                actor_display_name: actorProfile?.displayName ?? null,
                watch_id: watch.id,
                watch_brand: watch.brand,
                watch_model: watch.model,
                watch_brand_normalized: brandNormalized,
                watch_model_normalized: modelNormalized,
              },
            })
            // RESEARCH Pitfall 6 — invalidate the RECIPIENT's NotificationBell
            // cache so their unread dot lights up on next render. Bug fix (debug
            // session notifications-revalidate-tag-in-render): previously no
            // invalidation happened on the watch_overlap write path.
            revalidateTag(`viewer:${recipient.userId}`, 'max')
          }
        }
      } catch (err) {
        // Overlap lookup failures are non-fatal — never block the watch add.
        console.error('[addWatch] overlap lookup failed (non-fatal):', err)
      }
    }

    revalidatePath('/')

    // Phase 18 DISC-05 / DISC-06 — fan out 'explore' tag so the global
    // Trending + Gaining Traction rails (and the per-viewer Popular Collectors
    // rail, which also tags 'explore') recompute on next render. Cross-user
    // semantics via revalidateTag(tag, 'max') — Pitfall 4. Granularity is
    // intentionally broad (just 'explore') rather than per-rail, per RESEARCH
    // §Pattern 6 recommendation. Fires once regardless of status because
    // both Trending (owners + 0.5*wishlist) and Gaining Traction read the
    // denormalized counts from the catalog.
    revalidateTag('explore', 'max')

    return { success: true, data: watch }
  } catch (err) {
    console.error('[addWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to create watch' }
  }
}

/**
 * Update an existing watch.
 * Reads userId from session — callers do not pass userId (D-02).
 * Validates partial input, delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function editWatch(watchId: string, data: unknown): Promise<ActionResult<Watch>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  const parsed = updateWatchSchema.safeParse(data)
  if (!parsed.success) {
    const fieldErrors = parsed.error.flatten().fieldErrors
    const summary = Object.entries(fieldErrors)
      .map(([field, errors]) => `${field}: ${(errors ?? []).join(', ')}`)
      .join('; ')
    return { success: false, error: `Invalid watch data: ${summary}` }
  }

  try {
    // Phase 27 D-04 — status transition resets sort_order in the destination
    // group. Wishlist+grail share one group; owned+sold are a separate group
    // (Collection-tab reorder is deferred per CONTEXT, so we do not bump on
    // owned/sold transitions today). Only bump when:
    //   - parsed.data.status is 'wishlist' or 'grail', AND
    //   - the watch's CURRENT status is NOT wishlist/grail (transition INTO).
    // Within-group changes (wishlist ↔ grail) keep their slot — wishlist+grail
    // share the same sort_order space (D-05) so a within-group swap doesn't
    // change the bucket.
    let updatePayload: typeof parsed.data = parsed.data
    if (parsed.data.status === 'wishlist' || parsed.data.status === 'grail') {
      const currentRow = await watchDAL.getWatchById(user.id, watchId)
      const wasInWishlistGroup =
        currentRow?.status === 'wishlist' || currentRow?.status === 'grail'
      if (!wasInWishlistGroup) {
        const maxSort = await watchDAL.getMaxWishlistSortOrder(user.id)
        updatePayload = { ...parsed.data, sortOrder: maxSort + 1 }
      }
    }

    const watch = await watchDAL.updateWatch(user.id, watchId, updatePayload)
    revalidatePath('/')

    // Phase 18 DISC-05 / DISC-06 — same fan-out as addWatch. editWatch can
    // change status (owned ↔ wishlist ↔ sold ↔ grail), and each transition
    // shifts the catalog's denormalized counts (owners_count, wishlist_count)
    // on the next pg_cron refresh. Even non-status edits (brand/model fixes)
    // can affect Trending if they re-link the watch to a different catalog
    // row via the upsert path. Fan-out is the safe default.
    revalidateTag('explore', 'max')

    return { success: true, data: watch }
  } catch (err) {
    console.error('[editWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to update watch' }
  }
}

/**
 * Remove a watch from the collection.
 * Reads userId from session — callers do not pass userId (D-02).
 * Delegates to DAL, revalidates the home path on success.
 * Returns ActionResult — never throws across the boundary (D-12, D-15).
 */
export async function removeWatch(watchId: string): Promise<ActionResult<void>> {
  let user
  try { user = await getCurrentUser() } catch { return { success: false, error: 'Not authenticated' } }

  try {
    await watchDAL.deleteWatch(user.id, watchId)
    revalidatePath('/')

    // Phase 18 DISC-05 / DISC-06 — same fan-out as addWatch/editWatch.
    // DELETE on watches table → owners_count or wishlist_count decrements
    // on next pg_cron refresh, so the rails must recompute to reflect the
    // removal. Fan-out via revalidateTag(tag, 'max') — Pitfall 4.
    revalidateTag('explore', 'max')

    return { success: true, data: undefined }
  } catch (err) {
    console.error('[removeWatch] unexpected error:', err)
    if (err instanceof Error && err.message.includes('not found or access denied')) {
      return { success: false, error: 'Not found' }
    }
    return { success: false, error: 'Failed to delete watch' }
  }
}
